#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 9
#define X_TENSOR_COUNT 9
#define Y_TENSOR_COUNT 9
#define TENSOR_COUNT 18

static const uint32_t TOTAL_ELEMENTS = 5732; // floats in blob
static const uint32_t TOTAL_BYTES    = 22928; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 4290;
static const uint32_t Y_TOTAL_ELEMENTS = 1442;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_50_p50_2_1_A (1 inputs)
    1, // dense_aaab_x1_1_100_p100_2_1_A (1 inputs)
    2, // dense_aaac_x1_1_1280_p1280_2_1_A (1 inputs)
    3, // dense_aaad_x1_1_50_p50_2_4_A (1 inputs)
    4, // dense_aaae_x1_1_100_p100_2_4_A (1 inputs)
    5, // dense_aaaf_x1_1_1280_p1280_2_4_A (1 inputs)
    6, // dense_aaag_x1_1_50_p50_2_8_A (1 inputs)
    7, // dense_aaah_x1_1_100_p100_2_8_A (1 inputs)
    8, // dense_aaai_x1_1_1280_p1280_2_8_A (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_50_p50_2_1_A (1 outputs)
    1, // dense_aaab_x1_1_100_p100_2_1_A (1 outputs)
    2, // dense_aaac_x1_1_1280_p1280_2_1_A (1 outputs)
    3, // dense_aaad_x1_1_50_p50_2_4_A (1 outputs)
    4, // dense_aaae_x1_1_100_p100_2_4_A (1 outputs)
    5, // dense_aaaf_x1_1_1280_p1280_2_4_A (1 outputs)
    6, // dense_aaag_x1_1_50_p50_2_8_A (1 outputs)
    7, // dense_aaah_x1_1_100_p100_2_8_A (1 outputs)
    8, // dense_aaai_x1_1_1280_p1280_2_8_A (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // dense_aaaa_x1_1_50_p50_2_1_A (50 floats)
    50, // dense_aaab_x1_1_100_p100_2_1_A (100 floats)
    150, // dense_aaac_x1_1_1280_p1280_2_1_A (1280 floats)
    1430, // dense_aaad_x1_1_50_p50_2_4_A (50 floats)
    1480, // dense_aaae_x1_1_100_p100_2_4_A (100 floats)
    1580, // dense_aaaf_x1_1_1280_p1280_2_4_A (1280 floats)
    2860, // dense_aaag_x1_1_50_p50_2_8_A (50 floats)
    2910, // dense_aaah_x1_1_100_p100_2_8_A (100 floats)
    3010, // dense_aaai_x1_1_1280_p1280_2_8_A (1280 floats)
    // --- Y (ground-truth outputs) ---
    4290, // dense_aaaa_x1_1_50_p50_2_1_A (50 floats)
    4340, // dense_aaab_x1_1_100_p100_2_1_A (100 floats)
    4440, // dense_aaac_x1_1_1280_p1280_2_1_A (1280 floats)
    5720, // dense_aaad_x1_1_50_p50_2_4_A (2 floats)
    5722, // dense_aaae_x1_1_100_p100_2_4_A (2 floats)
    5724, // dense_aaaf_x1_1_1280_p1280_2_4_A (2 floats)
    5726, // dense_aaag_x1_1_50_p50_2_8_A (2 floats)
    5728, // dense_aaah_x1_1_100_p100_2_8_A (2 floats)
    5730, // dense_aaai_x1_1_1280_p1280_2_8_A (2 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    50, // dense_aaaa_x1_1_50_p50_2_1_A
    100, // dense_aaab_x1_1_100_p100_2_1_A
    1280, // dense_aaac_x1_1_1280_p1280_2_1_A
    50, // dense_aaad_x1_1_50_p50_2_4_A
    100, // dense_aaae_x1_1_100_p100_2_4_A
    1280, // dense_aaaf_x1_1_1280_p1280_2_4_A
    50, // dense_aaag_x1_1_50_p50_2_8_A
    100, // dense_aaah_x1_1_100_p100_2_8_A
    1280, // dense_aaai_x1_1_1280_p1280_2_8_A
    // --- Y (ground-truth outputs) ---
    50, // dense_aaaa_x1_1_50_p50_2_1_A
    100, // dense_aaab_x1_1_100_p100_2_1_A
    1280, // dense_aaac_x1_1_1280_p1280_2_1_A
    2, // dense_aaad_x1_1_50_p50_2_4_A
    2, // dense_aaae_x1_1_100_p100_2_4_A
    2, // dense_aaaf_x1_1_1280_p1280_2_4_A
    2, // dense_aaag_x1_1_50_p50_2_8_A
    2, // dense_aaah_x1_1_100_p100_2_8_A
    2, // dense_aaai_x1_1_1280_p1280_2_8_A
};
