#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 0).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 1
#define X_TENSOR_COUNT 1
#define Y_TENSOR_COUNT 1
#define TENSOR_COUNT 2

static const uint32_t TOTAL_ELEMENTS = 16810; // floats in blob
static const uint32_t TOTAL_BYTES    = 67240; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 1600;
static const uint32_t Y_TOTAL_ELEMENTS = 15210;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // conv_aaaa_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1600 floats)
    // --- Y (ground-truth outputs) ---
    1600, // conv_aaaa_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (15210 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    1600, // conv_aaaa_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1
    // --- Y (ground-truth outputs) ---
    15210, // conv_aaaa_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1
};
