#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 5
#define X_TENSOR_COUNT 15
#define Y_TENSOR_COUNT 15
#define TENSOR_COUNT 30

static const uint32_t TOTAL_ELEMENTS = 22050; // floats in blob
static const uint32_t TOTAL_BYTES    = 88200; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 11025;
static const uint32_t Y_TOTAL_ELEMENTS = 11025;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_1 (3 inputs)
    3, // lstm_aaab_x5_1_25_p25_25_1 (3 inputs)
    6, // lstm_aaac_x25_1_25_p25_25_1 (3 inputs)
    9, // lstm_aaad_x100_1_25_p25_25_1 (3 inputs)
    12, // lstm_aaae_x300_1_25_p25_25_1 (3 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_1 (3 outputs)
    3, // lstm_aaab_x5_1_25_p25_25_1 (3 outputs)
    6, // lstm_aaac_x25_1_25_p25_25_1 (3 outputs)
    9, // lstm_aaad_x100_1_25_p25_25_1 (3 outputs)
    12, // lstm_aaae_x300_1_25_p25_25_1 (3 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    25, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    50, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    75, // lstm_aaab_x5_1_25_p25_25_1 (125 floats)
    200, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    225, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    250, // lstm_aaac_x25_1_25_p25_25_1 (625 floats)
    875, // lstm_aaac_x25_1_25_p25_25_1 (25 floats)
    900, // lstm_aaac_x25_1_25_p25_25_1 (25 floats)
    925, // lstm_aaad_x100_1_25_p25_25_1 (2500 floats)
    3425, // lstm_aaad_x100_1_25_p25_25_1 (25 floats)
    3450, // lstm_aaad_x100_1_25_p25_25_1 (25 floats)
    3475, // lstm_aaae_x300_1_25_p25_25_1 (7500 floats)
    10975, // lstm_aaae_x300_1_25_p25_25_1 (25 floats)
    11000, // lstm_aaae_x300_1_25_p25_25_1 (25 floats)
    // --- Y (ground-truth outputs) ---
    11025, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    11050, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    11075, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    11100, // lstm_aaab_x5_1_25_p25_25_1 (125 floats)
    11225, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    11250, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    11275, // lstm_aaac_x25_1_25_p25_25_1 (625 floats)
    11900, // lstm_aaac_x25_1_25_p25_25_1 (25 floats)
    11925, // lstm_aaac_x25_1_25_p25_25_1 (25 floats)
    11950, // lstm_aaad_x100_1_25_p25_25_1 (2500 floats)
    14450, // lstm_aaad_x100_1_25_p25_25_1 (25 floats)
    14475, // lstm_aaad_x100_1_25_p25_25_1 (25 floats)
    14500, // lstm_aaae_x300_1_25_p25_25_1 (7500 floats)
    22000, // lstm_aaae_x300_1_25_p25_25_1 (25 floats)
    22025, // lstm_aaae_x300_1_25_p25_25_1 (25 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    125, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    625, // lstm_aaac_x25_1_25_p25_25_1
    25, // lstm_aaac_x25_1_25_p25_25_1
    25, // lstm_aaac_x25_1_25_p25_25_1
    2500, // lstm_aaad_x100_1_25_p25_25_1
    25, // lstm_aaad_x100_1_25_p25_25_1
    25, // lstm_aaad_x100_1_25_p25_25_1
    7500, // lstm_aaae_x300_1_25_p25_25_1
    25, // lstm_aaae_x300_1_25_p25_25_1
    25, // lstm_aaae_x300_1_25_p25_25_1
    // --- Y (ground-truth outputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    125, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    625, // lstm_aaac_x25_1_25_p25_25_1
    25, // lstm_aaac_x25_1_25_p25_25_1
    25, // lstm_aaac_x25_1_25_p25_25_1
    2500, // lstm_aaad_x100_1_25_p25_25_1
    25, // lstm_aaad_x100_1_25_p25_25_1
    25, // lstm_aaad_x100_1_25_p25_25_1
    7500, // lstm_aaae_x300_1_25_p25_25_1
    25, // lstm_aaae_x300_1_25_p25_25_1
    25, // lstm_aaae_x300_1_25_p25_25_1
};
