#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 18
#define X_TENSOR_COUNT 34
#define Y_TENSOR_COUNT 34
#define TENSOR_COUNT 68

static const uint32_t TOTAL_ELEMENTS = 570220; // floats in blob
static const uint32_t TOTAL_BYTES    = 2280880; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 59994;
static const uint32_t Y_TOTAL_ELEMENTS = 510226;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1 (1 inputs)
    1, // conv_aaab_x1_8_100_p1_10_1_A_1_10_pool_1_2_1_1 (1 inputs)
    2, // conv_aaac_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1 (1 inputs)
    3, // conv_aaad_x1_8_100_p1_30_2_A_1_20_pool_1_2_1_1 (1 inputs)
    4, // conv_aaae_x1_8_200_p1_30_2_A_1_20_pool_1_2_1_1 (1 inputs)
    5, // conv_aaaf_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1 (1 inputs)
    6, // dense_aaag_x1_1_50_p50_2_1_A (1 inputs)
    7, // dense_aaah_x1_1_1280_p1280_2_1_A (1 inputs)
    8, // dense_aaai_x1_1_50_p50_8_4_A (1 inputs)
    9, // dense_aaaj_x1_1_448_p448_8_4_A (1 inputs)
    10, // lstm_aaak_x1_1_10_p10_10_1 (3 inputs)
    13, // lstm_aaal_x1_1_60_p60_60_1 (3 inputs)
    16, // lstm_aaam_x1_1_200_p200_200_1 (3 inputs)
    19, // lstm_aaan_x1_1_10_p10_10_2 (3 inputs)
    22, // lstm_aaao_x1_1_60_p60_60_2 (3 inputs)
    25, // lstm_aaap_x1_1_200_p200_200_2 (3 inputs)
    28, // lstm_aaaq_x5_1_10_p10_10_2 (3 inputs)
    31, // lstm_aaar_x5_1_60_p60_60_2 (3 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1 (1 outputs)
    1, // conv_aaab_x1_8_100_p1_10_1_A_1_10_pool_1_2_1_1 (1 outputs)
    2, // conv_aaac_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1 (1 outputs)
    3, // conv_aaad_x1_8_100_p1_30_2_A_1_20_pool_1_2_1_1 (1 outputs)
    4, // conv_aaae_x1_8_200_p1_30_2_A_1_20_pool_1_2_1_1 (1 outputs)
    5, // conv_aaaf_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1 (1 outputs)
    6, // dense_aaag_x1_1_50_p50_2_1_A (1 outputs)
    7, // dense_aaah_x1_1_1280_p1280_2_1_A (1 outputs)
    8, // dense_aaai_x1_1_50_p50_8_4_A (1 outputs)
    9, // dense_aaaj_x1_1_448_p448_8_4_A (1 outputs)
    10, // lstm_aaak_x1_1_10_p10_10_1 (3 outputs)
    13, // lstm_aaal_x1_1_60_p60_60_1 (3 outputs)
    16, // lstm_aaam_x1_1_200_p200_200_1 (3 outputs)
    19, // lstm_aaan_x1_1_10_p10_10_2 (3 outputs)
    22, // lstm_aaao_x1_1_60_p60_60_2 (3 outputs)
    25, // lstm_aaap_x1_1_200_p200_200_2 (3 outputs)
    28, // lstm_aaaq_x5_1_10_p10_10_2 (3 outputs)
    31, // lstm_aaar_x5_1_60_p60_60_2 (3 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // conv_aaaa_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1 (400 floats)
    400, // conv_aaab_x1_8_100_p1_10_1_A_1_10_pool_1_2_1_1 (800 floats)
    1200, // conv_aaac_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1 (1600 floats)
    2800, // conv_aaad_x1_8_100_p1_30_2_A_1_20_pool_1_2_1_1 (800 floats)
    3600, // conv_aaae_x1_8_200_p1_30_2_A_1_20_pool_1_2_1_1 (1600 floats)
    5200, // conv_aaaf_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1 (50176 floats)
    55376, // dense_aaag_x1_1_50_p50_2_1_A (50 floats)
    55426, // dense_aaah_x1_1_1280_p1280_2_1_A (1280 floats)
    56706, // dense_aaai_x1_1_50_p50_8_4_A (50 floats)
    56756, // dense_aaaj_x1_1_448_p448_8_4_A (448 floats)
    57204, // lstm_aaak_x1_1_10_p10_10_1 (10 floats)
    57214, // lstm_aaak_x1_1_10_p10_10_1 (10 floats)
    57224, // lstm_aaak_x1_1_10_p10_10_1 (10 floats)
    57234, // lstm_aaal_x1_1_60_p60_60_1 (60 floats)
    57294, // lstm_aaal_x1_1_60_p60_60_1 (60 floats)
    57354, // lstm_aaal_x1_1_60_p60_60_1 (60 floats)
    57414, // lstm_aaam_x1_1_200_p200_200_1 (200 floats)
    57614, // lstm_aaam_x1_1_200_p200_200_1 (200 floats)
    57814, // lstm_aaam_x1_1_200_p200_200_1 (200 floats)
    58014, // lstm_aaan_x1_1_10_p10_10_2 (10 floats)
    58024, // lstm_aaan_x1_1_10_p10_10_2 (20 floats)
    58044, // lstm_aaan_x1_1_10_p10_10_2 (20 floats)
    58064, // lstm_aaao_x1_1_60_p60_60_2 (60 floats)
    58124, // lstm_aaao_x1_1_60_p60_60_2 (120 floats)
    58244, // lstm_aaao_x1_1_60_p60_60_2 (120 floats)
    58364, // lstm_aaap_x1_1_200_p200_200_2 (200 floats)
    58564, // lstm_aaap_x1_1_200_p200_200_2 (400 floats)
    58964, // lstm_aaap_x1_1_200_p200_200_2 (400 floats)
    59364, // lstm_aaaq_x5_1_10_p10_10_2 (50 floats)
    59414, // lstm_aaaq_x5_1_10_p10_10_2 (20 floats)
    59434, // lstm_aaaq_x5_1_10_p10_10_2 (20 floats)
    59454, // lstm_aaar_x5_1_60_p60_60_2 (300 floats)
    59754, // lstm_aaar_x5_1_60_p60_60_2 (120 floats)
    59874, // lstm_aaar_x5_1_60_p60_60_2 (120 floats)
    // --- Y (ground-truth outputs) ---
    59994, // conv_aaaa_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1 (3280 floats)
    63274, // conv_aaab_x1_8_100_p1_10_1_A_1_10_pool_1_2_1_1 (7280 floats)
    70554, // conv_aaac_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1 (15280 floats)
    85834, // conv_aaad_x1_8_100_p1_30_2_A_1_20_pool_1_2_1_1 (6000 floats)
    91834, // conv_aaae_x1_8_200_p1_30_2_A_1_20_pool_1_2_1_1 (12000 floats)
    103834, // conv_aaaf_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1 (462250 floats)
    566084, // dense_aaag_x1_1_50_p50_2_1_A (50 floats)
    566134, // dense_aaah_x1_1_1280_p1280_2_1_A (1280 floats)
    567414, // dense_aaai_x1_1_50_p50_8_4_A (8 floats)
    567422, // dense_aaaj_x1_1_448_p448_8_4_A (8 floats)
    567430, // lstm_aaak_x1_1_10_p10_10_1 (10 floats)
    567440, // lstm_aaak_x1_1_10_p10_10_1 (10 floats)
    567450, // lstm_aaak_x1_1_10_p10_10_1 (10 floats)
    567460, // lstm_aaal_x1_1_60_p60_60_1 (60 floats)
    567520, // lstm_aaal_x1_1_60_p60_60_1 (60 floats)
    567580, // lstm_aaal_x1_1_60_p60_60_1 (60 floats)
    567640, // lstm_aaam_x1_1_200_p200_200_1 (200 floats)
    567840, // lstm_aaam_x1_1_200_p200_200_1 (200 floats)
    568040, // lstm_aaam_x1_1_200_p200_200_1 (200 floats)
    568240, // lstm_aaan_x1_1_10_p10_10_2 (10 floats)
    568250, // lstm_aaan_x1_1_10_p10_10_2 (20 floats)
    568270, // lstm_aaan_x1_1_10_p10_10_2 (20 floats)
    568290, // lstm_aaao_x1_1_60_p60_60_2 (60 floats)
    568350, // lstm_aaao_x1_1_60_p60_60_2 (120 floats)
    568470, // lstm_aaao_x1_1_60_p60_60_2 (120 floats)
    568590, // lstm_aaap_x1_1_200_p200_200_2 (200 floats)
    568790, // lstm_aaap_x1_1_200_p200_200_2 (400 floats)
    569190, // lstm_aaap_x1_1_200_p200_200_2 (400 floats)
    569590, // lstm_aaaq_x5_1_10_p10_10_2 (50 floats)
    569640, // lstm_aaaq_x5_1_10_p10_10_2 (20 floats)
    569660, // lstm_aaaq_x5_1_10_p10_10_2 (20 floats)
    569680, // lstm_aaar_x5_1_60_p60_60_2 (300 floats)
    569980, // lstm_aaar_x5_1_60_p60_60_2 (120 floats)
    570100, // lstm_aaar_x5_1_60_p60_60_2 (120 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    400, // conv_aaaa_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1
    800, // conv_aaab_x1_8_100_p1_10_1_A_1_10_pool_1_2_1_1
    1600, // conv_aaac_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1
    800, // conv_aaad_x1_8_100_p1_30_2_A_1_20_pool_1_2_1_1
    1600, // conv_aaae_x1_8_200_p1_30_2_A_1_20_pool_1_2_1_1
    50176, // conv_aaaf_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1
    50, // dense_aaag_x1_1_50_p50_2_1_A
    1280, // dense_aaah_x1_1_1280_p1280_2_1_A
    50, // dense_aaai_x1_1_50_p50_8_4_A
    448, // dense_aaaj_x1_1_448_p448_8_4_A
    10, // lstm_aaak_x1_1_10_p10_10_1
    10, // lstm_aaak_x1_1_10_p10_10_1
    10, // lstm_aaak_x1_1_10_p10_10_1
    60, // lstm_aaal_x1_1_60_p60_60_1
    60, // lstm_aaal_x1_1_60_p60_60_1
    60, // lstm_aaal_x1_1_60_p60_60_1
    200, // lstm_aaam_x1_1_200_p200_200_1
    200, // lstm_aaam_x1_1_200_p200_200_1
    200, // lstm_aaam_x1_1_200_p200_200_1
    10, // lstm_aaan_x1_1_10_p10_10_2
    20, // lstm_aaan_x1_1_10_p10_10_2
    20, // lstm_aaan_x1_1_10_p10_10_2
    60, // lstm_aaao_x1_1_60_p60_60_2
    120, // lstm_aaao_x1_1_60_p60_60_2
    120, // lstm_aaao_x1_1_60_p60_60_2
    200, // lstm_aaap_x1_1_200_p200_200_2
    400, // lstm_aaap_x1_1_200_p200_200_2
    400, // lstm_aaap_x1_1_200_p200_200_2
    50, // lstm_aaaq_x5_1_10_p10_10_2
    20, // lstm_aaaq_x5_1_10_p10_10_2
    20, // lstm_aaaq_x5_1_10_p10_10_2
    300, // lstm_aaar_x5_1_60_p60_60_2
    120, // lstm_aaar_x5_1_60_p60_60_2
    120, // lstm_aaar_x5_1_60_p60_60_2
    // --- Y (ground-truth outputs) ---
    3280, // conv_aaaa_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1
    7280, // conv_aaab_x1_8_100_p1_10_1_A_1_10_pool_1_2_1_1
    15280, // conv_aaac_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1
    6000, // conv_aaad_x1_8_100_p1_30_2_A_1_20_pool_1_2_1_1
    12000, // conv_aaae_x1_8_200_p1_30_2_A_1_20_pool_1_2_1_1
    462250, // conv_aaaf_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1
    50, // dense_aaag_x1_1_50_p50_2_1_A
    1280, // dense_aaah_x1_1_1280_p1280_2_1_A
    8, // dense_aaai_x1_1_50_p50_8_4_A
    8, // dense_aaaj_x1_1_448_p448_8_4_A
    10, // lstm_aaak_x1_1_10_p10_10_1
    10, // lstm_aaak_x1_1_10_p10_10_1
    10, // lstm_aaak_x1_1_10_p10_10_1
    60, // lstm_aaal_x1_1_60_p60_60_1
    60, // lstm_aaal_x1_1_60_p60_60_1
    60, // lstm_aaal_x1_1_60_p60_60_1
    200, // lstm_aaam_x1_1_200_p200_200_1
    200, // lstm_aaam_x1_1_200_p200_200_1
    200, // lstm_aaam_x1_1_200_p200_200_1
    10, // lstm_aaan_x1_1_10_p10_10_2
    20, // lstm_aaan_x1_1_10_p10_10_2
    20, // lstm_aaan_x1_1_10_p10_10_2
    60, // lstm_aaao_x1_1_60_p60_60_2
    120, // lstm_aaao_x1_1_60_p60_60_2
    120, // lstm_aaao_x1_1_60_p60_60_2
    200, // lstm_aaap_x1_1_200_p200_200_2
    400, // lstm_aaap_x1_1_200_p200_200_2
    400, // lstm_aaap_x1_1_200_p200_200_2
    50, // lstm_aaaq_x5_1_10_p10_10_2
    20, // lstm_aaaq_x5_1_10_p10_10_2
    20, // lstm_aaaq_x5_1_10_p10_10_2
    300, // lstm_aaar_x5_1_60_p60_60_2
    120, // lstm_aaar_x5_1_60_p60_60_2
    120, // lstm_aaar_x5_1_60_p60_60_2
};
