#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 1
#define X_TENSOR_COUNT 1
#define Y_TENSOR_COUNT 1
#define TENSOR_COUNT 2

static const uint32_t TOTAL_ELEMENTS = 125; // floats in blob
static const uint32_t TOTAL_BYTES    = 500; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 25;
static const uint32_t Y_TOTAL_ELEMENTS = 100;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_25_p25_100_2_None (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_25_p25_100_2_None (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // dense_aaaa_x1_1_25_p25_100_2_None (25 floats)
    // --- Y (ground-truth outputs) ---
    25, // dense_aaaa_x1_1_25_p25_100_2_None (100 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // dense_aaaa_x1_1_25_p25_100_2_None
    // --- Y (ground-truth outputs) ---
    100, // dense_aaaa_x1_1_25_p25_100_2_None
};
