#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 12
#define X_TENSOR_COUNT 12
#define Y_TENSOR_COUNT 12
#define TENSOR_COUNT 24

static const uint32_t TOTAL_ELEMENTS = 1075; // floats in blob
static const uint32_t TOTAL_BYTES    = 4300; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 731;
static const uint32_t Y_TOTAL_ELEMENTS = 344;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_25_p25_2_2_None (1 inputs)
    1, // dense_aaab_x1_1_25_p25_2_3_None (1 inputs)
    2, // dense_aaac_x1_1_25_p25_2_4_None (1 inputs)
    3, // dense_aaad_x1_1_25_p25_2_5_None (1 inputs)
    4, // dense_aaae_x1_1_25_p25_2_6_None (1 inputs)
    5, // dense_aaaf_x1_1_25_p25_2_2_None (1 inputs)
    6, // dense_aaag_x1_1_50_p50_2_2_None (1 inputs)
    7, // dense_aaah_x1_1_100_p100_2_2_None (1 inputs)
    8, // dense_aaai_x1_1_150_p150_2_2_None (1 inputs)
    9, // dense_aaaj_x1_1_200_p200_2_2_None (1 inputs)
    10, // dense_aaak_x1_1_25_p25_100_2_None (1 inputs)
    11, // dense_aaal_x1_1_56_p56_224_2_None (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_25_p25_2_2_None (1 outputs)
    1, // dense_aaab_x1_1_25_p25_2_3_None (1 outputs)
    2, // dense_aaac_x1_1_25_p25_2_4_None (1 outputs)
    3, // dense_aaad_x1_1_25_p25_2_5_None (1 outputs)
    4, // dense_aaae_x1_1_25_p25_2_6_None (1 outputs)
    5, // dense_aaaf_x1_1_25_p25_2_2_None (1 outputs)
    6, // dense_aaag_x1_1_50_p50_2_2_None (1 outputs)
    7, // dense_aaah_x1_1_100_p100_2_2_None (1 outputs)
    8, // dense_aaai_x1_1_150_p150_2_2_None (1 outputs)
    9, // dense_aaaj_x1_1_200_p200_2_2_None (1 outputs)
    10, // dense_aaak_x1_1_25_p25_100_2_None (1 outputs)
    11, // dense_aaal_x1_1_56_p56_224_2_None (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // dense_aaaa_x1_1_25_p25_2_2_None (25 floats)
    25, // dense_aaab_x1_1_25_p25_2_3_None (25 floats)
    50, // dense_aaac_x1_1_25_p25_2_4_None (25 floats)
    75, // dense_aaad_x1_1_25_p25_2_5_None (25 floats)
    100, // dense_aaae_x1_1_25_p25_2_6_None (25 floats)
    125, // dense_aaaf_x1_1_25_p25_2_2_None (25 floats)
    150, // dense_aaag_x1_1_50_p50_2_2_None (50 floats)
    200, // dense_aaah_x1_1_100_p100_2_2_None (100 floats)
    300, // dense_aaai_x1_1_150_p150_2_2_None (150 floats)
    450, // dense_aaaj_x1_1_200_p200_2_2_None (200 floats)
    650, // dense_aaak_x1_1_25_p25_100_2_None (25 floats)
    675, // dense_aaal_x1_1_56_p56_224_2_None (56 floats)
    // --- Y (ground-truth outputs) ---
    731, // dense_aaaa_x1_1_25_p25_2_2_None (2 floats)
    733, // dense_aaab_x1_1_25_p25_2_3_None (2 floats)
    735, // dense_aaac_x1_1_25_p25_2_4_None (2 floats)
    737, // dense_aaad_x1_1_25_p25_2_5_None (2 floats)
    739, // dense_aaae_x1_1_25_p25_2_6_None (2 floats)
    741, // dense_aaaf_x1_1_25_p25_2_2_None (2 floats)
    743, // dense_aaag_x1_1_50_p50_2_2_None (2 floats)
    745, // dense_aaah_x1_1_100_p100_2_2_None (2 floats)
    747, // dense_aaai_x1_1_150_p150_2_2_None (2 floats)
    749, // dense_aaaj_x1_1_200_p200_2_2_None (2 floats)
    751, // dense_aaak_x1_1_25_p25_100_2_None (100 floats)
    851, // dense_aaal_x1_1_56_p56_224_2_None (224 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // dense_aaaa_x1_1_25_p25_2_2_None
    25, // dense_aaab_x1_1_25_p25_2_3_None
    25, // dense_aaac_x1_1_25_p25_2_4_None
    25, // dense_aaad_x1_1_25_p25_2_5_None
    25, // dense_aaae_x1_1_25_p25_2_6_None
    25, // dense_aaaf_x1_1_25_p25_2_2_None
    50, // dense_aaag_x1_1_50_p50_2_2_None
    100, // dense_aaah_x1_1_100_p100_2_2_None
    150, // dense_aaai_x1_1_150_p150_2_2_None
    200, // dense_aaaj_x1_1_200_p200_2_2_None
    25, // dense_aaak_x1_1_25_p25_100_2_None
    56, // dense_aaal_x1_1_56_p56_224_2_None
    // --- Y (ground-truth outputs) ---
    2, // dense_aaaa_x1_1_25_p25_2_2_None
    2, // dense_aaab_x1_1_25_p25_2_3_None
    2, // dense_aaac_x1_1_25_p25_2_4_None
    2, // dense_aaad_x1_1_25_p25_2_5_None
    2, // dense_aaae_x1_1_25_p25_2_6_None
    2, // dense_aaaf_x1_1_25_p25_2_2_None
    2, // dense_aaag_x1_1_50_p50_2_2_None
    2, // dense_aaah_x1_1_100_p100_2_2_None
    2, // dense_aaai_x1_1_150_p150_2_2_None
    2, // dense_aaaj_x1_1_200_p200_2_2_None
    100, // dense_aaak_x1_1_25_p25_100_2_None
    224, // dense_aaal_x1_1_56_p56_224_2_None
};
