#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 40
#define X_TENSOR_COUNT 40
#define Y_TENSOR_COUNT 40
#define TENSOR_COUNT 80

static const uint32_t TOTAL_ELEMENTS = 6418; // floats in blob
static const uint32_t TOTAL_BYTES    = 25672; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 5900;
static const uint32_t Y_TOTAL_ELEMENTS = 518;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_25_p25_2_2_None (1 inputs)
    1, // dense_aaab_x1_1_25_p25_2_3_None (1 inputs)
    2, // dense_aaac_x1_1_25_p25_2_4_None (1 inputs)
    3, // dense_aaad_x1_1_25_p25_2_5_None (1 inputs)
    4, // dense_aaae_x1_1_25_p25_2_6_None (1 inputs)
    5, // dense_aaaf_x1_1_25_p25_2_7_None (1 inputs)
    6, // dense_aaag_x1_1_25_p25_2_8_None (1 inputs)
    7, // dense_aaah_x1_1_25_p25_2_9_None (1 inputs)
    8, // dense_aaai_x1_1_25_p25_2_10_None (1 inputs)
    9, // dense_aaaj_x1_1_25_p25_2_11_None (1 inputs)
    10, // dense_aaak_x1_1_25_p25_2_12_None (1 inputs)
    11, // dense_aaal_x1_1_25_p25_2_13_None (1 inputs)
    12, // dense_aaam_x1_1_50_p50_2_2_None (1 inputs)
    13, // dense_aaan_x1_1_100_p100_2_2_None (1 inputs)
    14, // dense_aaao_x1_1_150_p150_2_2_None (1 inputs)
    15, // dense_aaap_x1_1_200_p200_2_2_None (1 inputs)
    16, // dense_aaaq_x1_1_250_p250_2_2_None (1 inputs)
    17, // dense_aaar_x1_1_300_p300_2_2_None (1 inputs)
    18, // dense_aaas_x1_1_350_p350_2_2_None (1 inputs)
    19, // dense_aaat_x1_1_400_p400_2_2_None (1 inputs)
    20, // dense_aaau_x1_1_450_p450_2_2_None (1 inputs)
    21, // dense_aaav_x1_1_500_p500_2_2_None (1 inputs)
    22, // dense_aaaw_x1_1_550_p550_2_2_None (1 inputs)
    23, // dense_aaax_x1_1_600_p600_2_2_None (1 inputs)
    24, // dense_aaay_x1_1_650_p650_2_2_None (1 inputs)
    25, // dense_aaaz_x1_1_700_p700_2_2_None (1 inputs)
    26, // dense_aaba_x1_1_25_p25_1_2_None (1 inputs)
    27, // dense_aabb_x1_1_25_p25_5_2_None (1 inputs)
    28, // dense_aabc_x1_1_25_p25_10_2_None (1 inputs)
    29, // dense_aabd_x1_1_25_p25_15_2_None (1 inputs)
    30, // dense_aabe_x1_1_25_p25_20_2_None (1 inputs)
    31, // dense_aabf_x1_1_25_p25_25_2_None (1 inputs)
    32, // dense_aabg_x1_1_25_p25_30_2_None (1 inputs)
    33, // dense_aabh_x1_1_25_p25_35_2_None (1 inputs)
    34, // dense_aabi_x1_1_25_p25_40_2_None (1 inputs)
    35, // dense_aabj_x1_1_25_p25_45_2_None (1 inputs)
    36, // dense_aabk_x1_1_25_p25_50_2_None (1 inputs)
    37, // dense_aabl_x1_1_25_p25_55_2_None (1 inputs)
    38, // dense_aabm_x1_1_25_p25_65_2_None (1 inputs)
    39, // dense_aabn_x1_1_25_p25_70_2_None (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_25_p25_2_2_None (1 outputs)
    1, // dense_aaab_x1_1_25_p25_2_3_None (1 outputs)
    2, // dense_aaac_x1_1_25_p25_2_4_None (1 outputs)
    3, // dense_aaad_x1_1_25_p25_2_5_None (1 outputs)
    4, // dense_aaae_x1_1_25_p25_2_6_None (1 outputs)
    5, // dense_aaaf_x1_1_25_p25_2_7_None (1 outputs)
    6, // dense_aaag_x1_1_25_p25_2_8_None (1 outputs)
    7, // dense_aaah_x1_1_25_p25_2_9_None (1 outputs)
    8, // dense_aaai_x1_1_25_p25_2_10_None (1 outputs)
    9, // dense_aaaj_x1_1_25_p25_2_11_None (1 outputs)
    10, // dense_aaak_x1_1_25_p25_2_12_None (1 outputs)
    11, // dense_aaal_x1_1_25_p25_2_13_None (1 outputs)
    12, // dense_aaam_x1_1_50_p50_2_2_None (1 outputs)
    13, // dense_aaan_x1_1_100_p100_2_2_None (1 outputs)
    14, // dense_aaao_x1_1_150_p150_2_2_None (1 outputs)
    15, // dense_aaap_x1_1_200_p200_2_2_None (1 outputs)
    16, // dense_aaaq_x1_1_250_p250_2_2_None (1 outputs)
    17, // dense_aaar_x1_1_300_p300_2_2_None (1 outputs)
    18, // dense_aaas_x1_1_350_p350_2_2_None (1 outputs)
    19, // dense_aaat_x1_1_400_p400_2_2_None (1 outputs)
    20, // dense_aaau_x1_1_450_p450_2_2_None (1 outputs)
    21, // dense_aaav_x1_1_500_p500_2_2_None (1 outputs)
    22, // dense_aaaw_x1_1_550_p550_2_2_None (1 outputs)
    23, // dense_aaax_x1_1_600_p600_2_2_None (1 outputs)
    24, // dense_aaay_x1_1_650_p650_2_2_None (1 outputs)
    25, // dense_aaaz_x1_1_700_p700_2_2_None (1 outputs)
    26, // dense_aaba_x1_1_25_p25_1_2_None (1 outputs)
    27, // dense_aabb_x1_1_25_p25_5_2_None (1 outputs)
    28, // dense_aabc_x1_1_25_p25_10_2_None (1 outputs)
    29, // dense_aabd_x1_1_25_p25_15_2_None (1 outputs)
    30, // dense_aabe_x1_1_25_p25_20_2_None (1 outputs)
    31, // dense_aabf_x1_1_25_p25_25_2_None (1 outputs)
    32, // dense_aabg_x1_1_25_p25_30_2_None (1 outputs)
    33, // dense_aabh_x1_1_25_p25_35_2_None (1 outputs)
    34, // dense_aabi_x1_1_25_p25_40_2_None (1 outputs)
    35, // dense_aabj_x1_1_25_p25_45_2_None (1 outputs)
    36, // dense_aabk_x1_1_25_p25_50_2_None (1 outputs)
    37, // dense_aabl_x1_1_25_p25_55_2_None (1 outputs)
    38, // dense_aabm_x1_1_25_p25_65_2_None (1 outputs)
    39, // dense_aabn_x1_1_25_p25_70_2_None (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // dense_aaaa_x1_1_25_p25_2_2_None (25 floats)
    25, // dense_aaab_x1_1_25_p25_2_3_None (25 floats)
    50, // dense_aaac_x1_1_25_p25_2_4_None (25 floats)
    75, // dense_aaad_x1_1_25_p25_2_5_None (25 floats)
    100, // dense_aaae_x1_1_25_p25_2_6_None (25 floats)
    125, // dense_aaaf_x1_1_25_p25_2_7_None (25 floats)
    150, // dense_aaag_x1_1_25_p25_2_8_None (25 floats)
    175, // dense_aaah_x1_1_25_p25_2_9_None (25 floats)
    200, // dense_aaai_x1_1_25_p25_2_10_None (25 floats)
    225, // dense_aaaj_x1_1_25_p25_2_11_None (25 floats)
    250, // dense_aaak_x1_1_25_p25_2_12_None (25 floats)
    275, // dense_aaal_x1_1_25_p25_2_13_None (25 floats)
    300, // dense_aaam_x1_1_50_p50_2_2_None (50 floats)
    350, // dense_aaan_x1_1_100_p100_2_2_None (100 floats)
    450, // dense_aaao_x1_1_150_p150_2_2_None (150 floats)
    600, // dense_aaap_x1_1_200_p200_2_2_None (200 floats)
    800, // dense_aaaq_x1_1_250_p250_2_2_None (250 floats)
    1050, // dense_aaar_x1_1_300_p300_2_2_None (300 floats)
    1350, // dense_aaas_x1_1_350_p350_2_2_None (350 floats)
    1700, // dense_aaat_x1_1_400_p400_2_2_None (400 floats)
    2100, // dense_aaau_x1_1_450_p450_2_2_None (450 floats)
    2550, // dense_aaav_x1_1_500_p500_2_2_None (500 floats)
    3050, // dense_aaaw_x1_1_550_p550_2_2_None (550 floats)
    3600, // dense_aaax_x1_1_600_p600_2_2_None (600 floats)
    4200, // dense_aaay_x1_1_650_p650_2_2_None (650 floats)
    4850, // dense_aaaz_x1_1_700_p700_2_2_None (700 floats)
    5550, // dense_aaba_x1_1_25_p25_1_2_None (25 floats)
    5575, // dense_aabb_x1_1_25_p25_5_2_None (25 floats)
    5600, // dense_aabc_x1_1_25_p25_10_2_None (25 floats)
    5625, // dense_aabd_x1_1_25_p25_15_2_None (25 floats)
    5650, // dense_aabe_x1_1_25_p25_20_2_None (25 floats)
    5675, // dense_aabf_x1_1_25_p25_25_2_None (25 floats)
    5700, // dense_aabg_x1_1_25_p25_30_2_None (25 floats)
    5725, // dense_aabh_x1_1_25_p25_35_2_None (25 floats)
    5750, // dense_aabi_x1_1_25_p25_40_2_None (25 floats)
    5775, // dense_aabj_x1_1_25_p25_45_2_None (25 floats)
    5800, // dense_aabk_x1_1_25_p25_50_2_None (25 floats)
    5825, // dense_aabl_x1_1_25_p25_55_2_None (25 floats)
    5850, // dense_aabm_x1_1_25_p25_65_2_None (25 floats)
    5875, // dense_aabn_x1_1_25_p25_70_2_None (25 floats)
    // --- Y (ground-truth outputs) ---
    5900, // dense_aaaa_x1_1_25_p25_2_2_None (2 floats)
    5902, // dense_aaab_x1_1_25_p25_2_3_None (2 floats)
    5904, // dense_aaac_x1_1_25_p25_2_4_None (2 floats)
    5906, // dense_aaad_x1_1_25_p25_2_5_None (2 floats)
    5908, // dense_aaae_x1_1_25_p25_2_6_None (2 floats)
    5910, // dense_aaaf_x1_1_25_p25_2_7_None (2 floats)
    5912, // dense_aaag_x1_1_25_p25_2_8_None (2 floats)
    5914, // dense_aaah_x1_1_25_p25_2_9_None (2 floats)
    5916, // dense_aaai_x1_1_25_p25_2_10_None (2 floats)
    5918, // dense_aaaj_x1_1_25_p25_2_11_None (2 floats)
    5920, // dense_aaak_x1_1_25_p25_2_12_None (2 floats)
    5922, // dense_aaal_x1_1_25_p25_2_13_None (2 floats)
    5924, // dense_aaam_x1_1_50_p50_2_2_None (2 floats)
    5926, // dense_aaan_x1_1_100_p100_2_2_None (2 floats)
    5928, // dense_aaao_x1_1_150_p150_2_2_None (2 floats)
    5930, // dense_aaap_x1_1_200_p200_2_2_None (2 floats)
    5932, // dense_aaaq_x1_1_250_p250_2_2_None (2 floats)
    5934, // dense_aaar_x1_1_300_p300_2_2_None (2 floats)
    5936, // dense_aaas_x1_1_350_p350_2_2_None (2 floats)
    5938, // dense_aaat_x1_1_400_p400_2_2_None (2 floats)
    5940, // dense_aaau_x1_1_450_p450_2_2_None (2 floats)
    5942, // dense_aaav_x1_1_500_p500_2_2_None (2 floats)
    5944, // dense_aaaw_x1_1_550_p550_2_2_None (2 floats)
    5946, // dense_aaax_x1_1_600_p600_2_2_None (2 floats)
    5948, // dense_aaay_x1_1_650_p650_2_2_None (2 floats)
    5950, // dense_aaaz_x1_1_700_p700_2_2_None (2 floats)
    5952, // dense_aaba_x1_1_25_p25_1_2_None (1 floats)
    5953, // dense_aabb_x1_1_25_p25_5_2_None (5 floats)
    5958, // dense_aabc_x1_1_25_p25_10_2_None (10 floats)
    5968, // dense_aabd_x1_1_25_p25_15_2_None (15 floats)
    5983, // dense_aabe_x1_1_25_p25_20_2_None (20 floats)
    6003, // dense_aabf_x1_1_25_p25_25_2_None (25 floats)
    6028, // dense_aabg_x1_1_25_p25_30_2_None (30 floats)
    6058, // dense_aabh_x1_1_25_p25_35_2_None (35 floats)
    6093, // dense_aabi_x1_1_25_p25_40_2_None (40 floats)
    6133, // dense_aabj_x1_1_25_p25_45_2_None (45 floats)
    6178, // dense_aabk_x1_1_25_p25_50_2_None (50 floats)
    6228, // dense_aabl_x1_1_25_p25_55_2_None (55 floats)
    6283, // dense_aabm_x1_1_25_p25_65_2_None (65 floats)
    6348, // dense_aabn_x1_1_25_p25_70_2_None (70 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // dense_aaaa_x1_1_25_p25_2_2_None
    25, // dense_aaab_x1_1_25_p25_2_3_None
    25, // dense_aaac_x1_1_25_p25_2_4_None
    25, // dense_aaad_x1_1_25_p25_2_5_None
    25, // dense_aaae_x1_1_25_p25_2_6_None
    25, // dense_aaaf_x1_1_25_p25_2_7_None
    25, // dense_aaag_x1_1_25_p25_2_8_None
    25, // dense_aaah_x1_1_25_p25_2_9_None
    25, // dense_aaai_x1_1_25_p25_2_10_None
    25, // dense_aaaj_x1_1_25_p25_2_11_None
    25, // dense_aaak_x1_1_25_p25_2_12_None
    25, // dense_aaal_x1_1_25_p25_2_13_None
    50, // dense_aaam_x1_1_50_p50_2_2_None
    100, // dense_aaan_x1_1_100_p100_2_2_None
    150, // dense_aaao_x1_1_150_p150_2_2_None
    200, // dense_aaap_x1_1_200_p200_2_2_None
    250, // dense_aaaq_x1_1_250_p250_2_2_None
    300, // dense_aaar_x1_1_300_p300_2_2_None
    350, // dense_aaas_x1_1_350_p350_2_2_None
    400, // dense_aaat_x1_1_400_p400_2_2_None
    450, // dense_aaau_x1_1_450_p450_2_2_None
    500, // dense_aaav_x1_1_500_p500_2_2_None
    550, // dense_aaaw_x1_1_550_p550_2_2_None
    600, // dense_aaax_x1_1_600_p600_2_2_None
    650, // dense_aaay_x1_1_650_p650_2_2_None
    700, // dense_aaaz_x1_1_700_p700_2_2_None
    25, // dense_aaba_x1_1_25_p25_1_2_None
    25, // dense_aabb_x1_1_25_p25_5_2_None
    25, // dense_aabc_x1_1_25_p25_10_2_None
    25, // dense_aabd_x1_1_25_p25_15_2_None
    25, // dense_aabe_x1_1_25_p25_20_2_None
    25, // dense_aabf_x1_1_25_p25_25_2_None
    25, // dense_aabg_x1_1_25_p25_30_2_None
    25, // dense_aabh_x1_1_25_p25_35_2_None
    25, // dense_aabi_x1_1_25_p25_40_2_None
    25, // dense_aabj_x1_1_25_p25_45_2_None
    25, // dense_aabk_x1_1_25_p25_50_2_None
    25, // dense_aabl_x1_1_25_p25_55_2_None
    25, // dense_aabm_x1_1_25_p25_65_2_None
    25, // dense_aabn_x1_1_25_p25_70_2_None
    // --- Y (ground-truth outputs) ---
    2, // dense_aaaa_x1_1_25_p25_2_2_None
    2, // dense_aaab_x1_1_25_p25_2_3_None
    2, // dense_aaac_x1_1_25_p25_2_4_None
    2, // dense_aaad_x1_1_25_p25_2_5_None
    2, // dense_aaae_x1_1_25_p25_2_6_None
    2, // dense_aaaf_x1_1_25_p25_2_7_None
    2, // dense_aaag_x1_1_25_p25_2_8_None
    2, // dense_aaah_x1_1_25_p25_2_9_None
    2, // dense_aaai_x1_1_25_p25_2_10_None
    2, // dense_aaaj_x1_1_25_p25_2_11_None
    2, // dense_aaak_x1_1_25_p25_2_12_None
    2, // dense_aaal_x1_1_25_p25_2_13_None
    2, // dense_aaam_x1_1_50_p50_2_2_None
    2, // dense_aaan_x1_1_100_p100_2_2_None
    2, // dense_aaao_x1_1_150_p150_2_2_None
    2, // dense_aaap_x1_1_200_p200_2_2_None
    2, // dense_aaaq_x1_1_250_p250_2_2_None
    2, // dense_aaar_x1_1_300_p300_2_2_None
    2, // dense_aaas_x1_1_350_p350_2_2_None
    2, // dense_aaat_x1_1_400_p400_2_2_None
    2, // dense_aaau_x1_1_450_p450_2_2_None
    2, // dense_aaav_x1_1_500_p500_2_2_None
    2, // dense_aaaw_x1_1_550_p550_2_2_None
    2, // dense_aaax_x1_1_600_p600_2_2_None
    2, // dense_aaay_x1_1_650_p650_2_2_None
    2, // dense_aaaz_x1_1_700_p700_2_2_None
    1, // dense_aaba_x1_1_25_p25_1_2_None
    5, // dense_aabb_x1_1_25_p25_5_2_None
    10, // dense_aabc_x1_1_25_p25_10_2_None
    15, // dense_aabd_x1_1_25_p25_15_2_None
    20, // dense_aabe_x1_1_25_p25_20_2_None
    25, // dense_aabf_x1_1_25_p25_25_2_None
    30, // dense_aabg_x1_1_25_p25_30_2_None
    35, // dense_aabh_x1_1_25_p25_35_2_None
    40, // dense_aabi_x1_1_25_p25_40_2_None
    45, // dense_aabj_x1_1_25_p25_45_2_None
    50, // dense_aabk_x1_1_25_p25_50_2_None
    55, // dense_aabl_x1_1_25_p25_55_2_None
    65, // dense_aabm_x1_1_25_p25_65_2_None
    70, // dense_aabn_x1_1_25_p25_70_2_None
};
