#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 10
#define X_TENSOR_COUNT 10
#define Y_TENSOR_COUNT 10
#define TENSOR_COUNT 20

static const uint32_t TOTAL_ELEMENTS = 623412; // floats in blob
static const uint32_t TOTAL_BYTES    = 2493648; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 109872;
static const uint32_t Y_TOTAL_ELEMENTS = 513540;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_2_50_p1_10_1_A_1_5_pool_1_2_1_1 (1 inputs)
    1, // conv_aaab_x1_2_10_p1_10_1_A_1_5_pool_1_2_1_1 (1 inputs)
    2, // conv_aaac_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1 (1 inputs)
    3, // conv_aaad_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1 (1 inputs)
    4, // conv_aaae_x1_8_100_p1_40_4_A_1_10_pool_1_2_1_1 (1 inputs)
    5, // conv_aaaf_x1_8_200_p1_40_4_A_1_10_pool_1_2_1_1 (1 inputs)
    6, // conv_aaag_x1_50_50_p1_10_1_A_10_10_pool_2_2_1_1 (1 inputs)
    7, // conv_aaah_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1 (1 inputs)
    8, // conv_aaai_x1_50_50_p1_40_4_A_10_10_pool_2_2_1_1 (1 inputs)
    9, // conv_aaaj_x1_224_224_p1_40_4_A_10_10_pool_2_2_1_1 (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_2_50_p1_10_1_A_1_5_pool_1_2_1_1 (1 outputs)
    1, // conv_aaab_x1_2_10_p1_10_1_A_1_5_pool_1_2_1_1 (1 outputs)
    2, // conv_aaac_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1 (1 outputs)
    3, // conv_aaad_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1 (1 outputs)
    4, // conv_aaae_x1_8_100_p1_40_4_A_1_10_pool_1_2_1_1 (1 outputs)
    5, // conv_aaaf_x1_8_200_p1_40_4_A_1_10_pool_1_2_1_1 (1 outputs)
    6, // conv_aaag_x1_50_50_p1_10_1_A_10_10_pool_2_2_1_1 (1 outputs)
    7, // conv_aaah_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1 (1 outputs)
    8, // conv_aaai_x1_50_50_p1_40_4_A_10_10_pool_2_2_1_1 (1 outputs)
    9, // conv_aaaj_x1_224_224_p1_40_4_A_10_10_pool_2_2_1_1 (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // conv_aaaa_x1_2_50_p1_10_1_A_1_5_pool_1_2_1_1 (100 floats)
    100, // conv_aaab_x1_2_10_p1_10_1_A_1_5_pool_1_2_1_1 (20 floats)
    120, // conv_aaac_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1 (400 floats)
    520, // conv_aaad_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1 (1600 floats)
    2120, // conv_aaae_x1_8_100_p1_40_4_A_1_10_pool_1_2_1_1 (800 floats)
    2920, // conv_aaaf_x1_8_200_p1_40_4_A_1_10_pool_1_2_1_1 (1600 floats)
    4520, // conv_aaag_x1_50_50_p1_10_1_A_10_10_pool_2_2_1_1 (2500 floats)
    7020, // conv_aaah_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1 (50176 floats)
    57196, // conv_aaai_x1_50_50_p1_40_4_A_10_10_pool_2_2_1_1 (2500 floats)
    59696, // conv_aaaj_x1_224_224_p1_40_4_A_10_10_pool_2_2_1_1 (50176 floats)
    // --- Y (ground-truth outputs) ---
    109872, // conv_aaaa_x1_2_50_p1_10_1_A_1_5_pool_1_2_1_1 (920 floats)
    110792, // conv_aaab_x1_2_10_p1_10_1_A_1_5_pool_1_2_1_1 (120 floats)
    110912, // conv_aaac_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1 (3280 floats)
    114192, // conv_aaad_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1 (15280 floats)
    129472, // conv_aaae_x1_8_100_p1_40_4_A_1_10_pool_1_2_1_1 (2240 floats)
    131712, // conv_aaaf_x1_8_200_p1_40_4_A_1_10_pool_1_2_1_1 (4160 floats)
    135872, // conv_aaag_x1_50_50_p1_10_1_A_10_10_pool_2_2_1_1 (16810 floats)
    152682, // conv_aaah_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1 (462250 floats)
    614932, // conv_aaai_x1_50_50_p1_40_4_A_10_10_pool_2_2_1_1 (640 floats)
    615572, // conv_aaaj_x1_224_224_p1_40_4_A_10_10_pool_2_2_1_1 (7840 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    100, // conv_aaaa_x1_2_50_p1_10_1_A_1_5_pool_1_2_1_1
    20, // conv_aaab_x1_2_10_p1_10_1_A_1_5_pool_1_2_1_1
    400, // conv_aaac_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1
    1600, // conv_aaad_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1
    800, // conv_aaae_x1_8_100_p1_40_4_A_1_10_pool_1_2_1_1
    1600, // conv_aaaf_x1_8_200_p1_40_4_A_1_10_pool_1_2_1_1
    2500, // conv_aaag_x1_50_50_p1_10_1_A_10_10_pool_2_2_1_1
    50176, // conv_aaah_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1
    2500, // conv_aaai_x1_50_50_p1_40_4_A_10_10_pool_2_2_1_1
    50176, // conv_aaaj_x1_224_224_p1_40_4_A_10_10_pool_2_2_1_1
    // --- Y (ground-truth outputs) ---
    920, // conv_aaaa_x1_2_50_p1_10_1_A_1_5_pool_1_2_1_1
    120, // conv_aaab_x1_2_10_p1_10_1_A_1_5_pool_1_2_1_1
    3280, // conv_aaac_x1_8_50_p1_10_1_A_1_10_pool_1_2_1_1
    15280, // conv_aaad_x1_8_200_p1_10_1_A_1_10_pool_1_2_1_1
    2240, // conv_aaae_x1_8_100_p1_40_4_A_1_10_pool_1_2_1_1
    4160, // conv_aaaf_x1_8_200_p1_40_4_A_1_10_pool_1_2_1_1
    16810, // conv_aaag_x1_50_50_p1_10_1_A_10_10_pool_2_2_1_1
    462250, // conv_aaah_x1_224_224_p1_10_1_A_10_10_pool_2_2_1_1
    640, // conv_aaai_x1_50_50_p1_40_4_A_10_10_pool_2_2_1_1
    7840, // conv_aaaj_x1_224_224_p1_40_4_A_10_10_pool_2_2_1_1
};
