#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 1).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 20
#define X_TENSOR_COUNT 20
#define Y_TENSOR_COUNT 20
#define TENSOR_COUNT 40

static const uint32_t TOTAL_ELEMENTS = 1040; // floats in blob
static const uint32_t TOTAL_BYTES    = 4160; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 1000;
static const uint32_t Y_TOTAL_ELEMENTS = 40;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_50_p50_2_2_None (1 inputs)
    1, // dense_aaab_x1_1_50_p50_2_3_None (1 inputs)
    2, // dense_aaac_x1_1_50_p50_2_4_None (1 inputs)
    3, // dense_aaad_x1_1_50_p50_2_5_None (1 inputs)
    4, // dense_aaae_x1_1_50_p50_2_6_None (1 inputs)
    5, // dense_aaaf_x1_1_50_p50_2_7_None (1 inputs)
    6, // dense_aaag_x1_1_50_p50_2_8_None (1 inputs)
    7, // dense_aaah_x1_1_50_p50_2_9_None (1 inputs)
    8, // dense_aaai_x1_1_50_p50_2_10_None (1 inputs)
    9, // dense_aaaj_x1_1_50_p50_2_11_None (1 inputs)
    10, // dense_aaak_x1_1_50_p50_2_12_None (1 inputs)
    11, // dense_aaal_x1_1_50_p50_2_13_None (1 inputs)
    12, // dense_aaam_x1_1_50_p50_2_14_None (1 inputs)
    13, // dense_aaan_x1_1_50_p50_2_15_None (1 inputs)
    14, // dense_aaao_x1_1_50_p50_2_16_None (1 inputs)
    15, // dense_aaap_x1_1_50_p50_2_17_None (1 inputs)
    16, // dense_aaaq_x1_1_50_p50_2_18_None (1 inputs)
    17, // dense_aaar_x1_1_50_p50_2_19_None (1 inputs)
    18, // dense_aaas_x1_1_50_p50_2_20_None (1 inputs)
    19, // dense_aaat_x1_1_50_p50_2_21_None (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_50_p50_2_2_None (1 outputs)
    1, // dense_aaab_x1_1_50_p50_2_3_None (1 outputs)
    2, // dense_aaac_x1_1_50_p50_2_4_None (1 outputs)
    3, // dense_aaad_x1_1_50_p50_2_5_None (1 outputs)
    4, // dense_aaae_x1_1_50_p50_2_6_None (1 outputs)
    5, // dense_aaaf_x1_1_50_p50_2_7_None (1 outputs)
    6, // dense_aaag_x1_1_50_p50_2_8_None (1 outputs)
    7, // dense_aaah_x1_1_50_p50_2_9_None (1 outputs)
    8, // dense_aaai_x1_1_50_p50_2_10_None (1 outputs)
    9, // dense_aaaj_x1_1_50_p50_2_11_None (1 outputs)
    10, // dense_aaak_x1_1_50_p50_2_12_None (1 outputs)
    11, // dense_aaal_x1_1_50_p50_2_13_None (1 outputs)
    12, // dense_aaam_x1_1_50_p50_2_14_None (1 outputs)
    13, // dense_aaan_x1_1_50_p50_2_15_None (1 outputs)
    14, // dense_aaao_x1_1_50_p50_2_16_None (1 outputs)
    15, // dense_aaap_x1_1_50_p50_2_17_None (1 outputs)
    16, // dense_aaaq_x1_1_50_p50_2_18_None (1 outputs)
    17, // dense_aaar_x1_1_50_p50_2_19_None (1 outputs)
    18, // dense_aaas_x1_1_50_p50_2_20_None (1 outputs)
    19, // dense_aaat_x1_1_50_p50_2_21_None (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // dense_aaaa_x1_1_50_p50_2_2_None (50 floats)
    50, // dense_aaab_x1_1_50_p50_2_3_None (50 floats)
    100, // dense_aaac_x1_1_50_p50_2_4_None (50 floats)
    150, // dense_aaad_x1_1_50_p50_2_5_None (50 floats)
    200, // dense_aaae_x1_1_50_p50_2_6_None (50 floats)
    250, // dense_aaaf_x1_1_50_p50_2_7_None (50 floats)
    300, // dense_aaag_x1_1_50_p50_2_8_None (50 floats)
    350, // dense_aaah_x1_1_50_p50_2_9_None (50 floats)
    400, // dense_aaai_x1_1_50_p50_2_10_None (50 floats)
    450, // dense_aaaj_x1_1_50_p50_2_11_None (50 floats)
    500, // dense_aaak_x1_1_50_p50_2_12_None (50 floats)
    550, // dense_aaal_x1_1_50_p50_2_13_None (50 floats)
    600, // dense_aaam_x1_1_50_p50_2_14_None (50 floats)
    650, // dense_aaan_x1_1_50_p50_2_15_None (50 floats)
    700, // dense_aaao_x1_1_50_p50_2_16_None (50 floats)
    750, // dense_aaap_x1_1_50_p50_2_17_None (50 floats)
    800, // dense_aaaq_x1_1_50_p50_2_18_None (50 floats)
    850, // dense_aaar_x1_1_50_p50_2_19_None (50 floats)
    900, // dense_aaas_x1_1_50_p50_2_20_None (50 floats)
    950, // dense_aaat_x1_1_50_p50_2_21_None (50 floats)
    // --- Y (ground-truth outputs) ---
    1000, // dense_aaaa_x1_1_50_p50_2_2_None (2 floats)
    1002, // dense_aaab_x1_1_50_p50_2_3_None (2 floats)
    1004, // dense_aaac_x1_1_50_p50_2_4_None (2 floats)
    1006, // dense_aaad_x1_1_50_p50_2_5_None (2 floats)
    1008, // dense_aaae_x1_1_50_p50_2_6_None (2 floats)
    1010, // dense_aaaf_x1_1_50_p50_2_7_None (2 floats)
    1012, // dense_aaag_x1_1_50_p50_2_8_None (2 floats)
    1014, // dense_aaah_x1_1_50_p50_2_9_None (2 floats)
    1016, // dense_aaai_x1_1_50_p50_2_10_None (2 floats)
    1018, // dense_aaaj_x1_1_50_p50_2_11_None (2 floats)
    1020, // dense_aaak_x1_1_50_p50_2_12_None (2 floats)
    1022, // dense_aaal_x1_1_50_p50_2_13_None (2 floats)
    1024, // dense_aaam_x1_1_50_p50_2_14_None (2 floats)
    1026, // dense_aaan_x1_1_50_p50_2_15_None (2 floats)
    1028, // dense_aaao_x1_1_50_p50_2_16_None (2 floats)
    1030, // dense_aaap_x1_1_50_p50_2_17_None (2 floats)
    1032, // dense_aaaq_x1_1_50_p50_2_18_None (2 floats)
    1034, // dense_aaar_x1_1_50_p50_2_19_None (2 floats)
    1036, // dense_aaas_x1_1_50_p50_2_20_None (2 floats)
    1038, // dense_aaat_x1_1_50_p50_2_21_None (2 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    50, // dense_aaaa_x1_1_50_p50_2_2_None
    50, // dense_aaab_x1_1_50_p50_2_3_None
    50, // dense_aaac_x1_1_50_p50_2_4_None
    50, // dense_aaad_x1_1_50_p50_2_5_None
    50, // dense_aaae_x1_1_50_p50_2_6_None
    50, // dense_aaaf_x1_1_50_p50_2_7_None
    50, // dense_aaag_x1_1_50_p50_2_8_None
    50, // dense_aaah_x1_1_50_p50_2_9_None
    50, // dense_aaai_x1_1_50_p50_2_10_None
    50, // dense_aaaj_x1_1_50_p50_2_11_None
    50, // dense_aaak_x1_1_50_p50_2_12_None
    50, // dense_aaal_x1_1_50_p50_2_13_None
    50, // dense_aaam_x1_1_50_p50_2_14_None
    50, // dense_aaan_x1_1_50_p50_2_15_None
    50, // dense_aaao_x1_1_50_p50_2_16_None
    50, // dense_aaap_x1_1_50_p50_2_17_None
    50, // dense_aaaq_x1_1_50_p50_2_18_None
    50, // dense_aaar_x1_1_50_p50_2_19_None
    50, // dense_aaas_x1_1_50_p50_2_20_None
    50, // dense_aaat_x1_1_50_p50_2_21_None
    // --- Y (ground-truth outputs) ---
    2, // dense_aaaa_x1_1_50_p50_2_2_None
    2, // dense_aaab_x1_1_50_p50_2_3_None
    2, // dense_aaac_x1_1_50_p50_2_4_None
    2, // dense_aaad_x1_1_50_p50_2_5_None
    2, // dense_aaae_x1_1_50_p50_2_6_None
    2, // dense_aaaf_x1_1_50_p50_2_7_None
    2, // dense_aaag_x1_1_50_p50_2_8_None
    2, // dense_aaah_x1_1_50_p50_2_9_None
    2, // dense_aaai_x1_1_50_p50_2_10_None
    2, // dense_aaaj_x1_1_50_p50_2_11_None
    2, // dense_aaak_x1_1_50_p50_2_12_None
    2, // dense_aaal_x1_1_50_p50_2_13_None
    2, // dense_aaam_x1_1_50_p50_2_14_None
    2, // dense_aaan_x1_1_50_p50_2_15_None
    2, // dense_aaao_x1_1_50_p50_2_16_None
    2, // dense_aaap_x1_1_50_p50_2_17_None
    2, // dense_aaaq_x1_1_50_p50_2_18_None
    2, // dense_aaar_x1_1_50_p50_2_19_None
    2, // dense_aaas_x1_1_50_p50_2_20_None
    2, // dense_aaat_x1_1_50_p50_2_21_None
};
