#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 30
#define X_TENSOR_COUNT 30
#define Y_TENSOR_COUNT 30
#define TENSOR_COUNT 60

static const uint32_t TOTAL_ELEMENTS = 3551; // floats in blob
static const uint32_t TOTAL_BYTES    = 14204; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 3250;
static const uint32_t Y_TOTAL_ELEMENTS = 301;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_25_p25_2_2_None (1 inputs)
    1, // dense_aaab_x1_1_25_p25_2_3_None (1 inputs)
    2, // dense_aaac_x1_1_25_p25_2_4_None (1 inputs)
    3, // dense_aaad_x1_1_25_p25_2_5_None (1 inputs)
    4, // dense_aaae_x1_1_25_p25_2_6_None (1 inputs)
    5, // dense_aaaf_x1_1_25_p25_2_7_None (1 inputs)
    6, // dense_aaag_x1_1_25_p25_2_8_None (1 inputs)
    7, // dense_aaah_x1_1_25_p25_2_9_None (1 inputs)
    8, // dense_aaai_x1_1_25_p25_2_10_None (1 inputs)
    9, // dense_aaaj_x1_1_25_p25_2_11_None (1 inputs)
    10, // dense_aaak_x1_1_50_p50_2_2_None (1 inputs)
    11, // dense_aaal_x1_1_100_p100_2_2_None (1 inputs)
    12, // dense_aaam_x1_1_150_p150_2_2_None (1 inputs)
    13, // dense_aaan_x1_1_200_p200_2_2_None (1 inputs)
    14, // dense_aaao_x1_1_250_p250_2_2_None (1 inputs)
    15, // dense_aaap_x1_1_300_p300_2_2_None (1 inputs)
    16, // dense_aaaq_x1_1_350_p350_2_2_None (1 inputs)
    17, // dense_aaar_x1_1_400_p400_2_2_None (1 inputs)
    18, // dense_aaas_x1_1_450_p450_2_2_None (1 inputs)
    19, // dense_aaat_x1_1_500_p500_2_2_None (1 inputs)
    20, // dense_aaau_x1_1_25_p25_1_2_None (1 inputs)
    21, // dense_aaav_x1_1_25_p25_5_2_None (1 inputs)
    22, // dense_aaaw_x1_1_25_p25_10_2_None (1 inputs)
    23, // dense_aaax_x1_1_25_p25_20_2_None (1 inputs)
    24, // dense_aaay_x1_1_25_p25_25_2_None (1 inputs)
    25, // dense_aaaz_x1_1_25_p25_30_2_None (1 inputs)
    26, // dense_aaba_x1_1_25_p25_35_2_None (1 inputs)
    27, // dense_aabb_x1_1_25_p25_40_2_None (1 inputs)
    28, // dense_aabc_x1_1_25_p25_45_2_None (1 inputs)
    29, // dense_aabd_x1_1_25_p25_50_2_None (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // dense_aaaa_x1_1_25_p25_2_2_None (1 outputs)
    1, // dense_aaab_x1_1_25_p25_2_3_None (1 outputs)
    2, // dense_aaac_x1_1_25_p25_2_4_None (1 outputs)
    3, // dense_aaad_x1_1_25_p25_2_5_None (1 outputs)
    4, // dense_aaae_x1_1_25_p25_2_6_None (1 outputs)
    5, // dense_aaaf_x1_1_25_p25_2_7_None (1 outputs)
    6, // dense_aaag_x1_1_25_p25_2_8_None (1 outputs)
    7, // dense_aaah_x1_1_25_p25_2_9_None (1 outputs)
    8, // dense_aaai_x1_1_25_p25_2_10_None (1 outputs)
    9, // dense_aaaj_x1_1_25_p25_2_11_None (1 outputs)
    10, // dense_aaak_x1_1_50_p50_2_2_None (1 outputs)
    11, // dense_aaal_x1_1_100_p100_2_2_None (1 outputs)
    12, // dense_aaam_x1_1_150_p150_2_2_None (1 outputs)
    13, // dense_aaan_x1_1_200_p200_2_2_None (1 outputs)
    14, // dense_aaao_x1_1_250_p250_2_2_None (1 outputs)
    15, // dense_aaap_x1_1_300_p300_2_2_None (1 outputs)
    16, // dense_aaaq_x1_1_350_p350_2_2_None (1 outputs)
    17, // dense_aaar_x1_1_400_p400_2_2_None (1 outputs)
    18, // dense_aaas_x1_1_450_p450_2_2_None (1 outputs)
    19, // dense_aaat_x1_1_500_p500_2_2_None (1 outputs)
    20, // dense_aaau_x1_1_25_p25_1_2_None (1 outputs)
    21, // dense_aaav_x1_1_25_p25_5_2_None (1 outputs)
    22, // dense_aaaw_x1_1_25_p25_10_2_None (1 outputs)
    23, // dense_aaax_x1_1_25_p25_20_2_None (1 outputs)
    24, // dense_aaay_x1_1_25_p25_25_2_None (1 outputs)
    25, // dense_aaaz_x1_1_25_p25_30_2_None (1 outputs)
    26, // dense_aaba_x1_1_25_p25_35_2_None (1 outputs)
    27, // dense_aabb_x1_1_25_p25_40_2_None (1 outputs)
    28, // dense_aabc_x1_1_25_p25_45_2_None (1 outputs)
    29, // dense_aabd_x1_1_25_p25_50_2_None (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // dense_aaaa_x1_1_25_p25_2_2_None (25 floats)
    25, // dense_aaab_x1_1_25_p25_2_3_None (25 floats)
    50, // dense_aaac_x1_1_25_p25_2_4_None (25 floats)
    75, // dense_aaad_x1_1_25_p25_2_5_None (25 floats)
    100, // dense_aaae_x1_1_25_p25_2_6_None (25 floats)
    125, // dense_aaaf_x1_1_25_p25_2_7_None (25 floats)
    150, // dense_aaag_x1_1_25_p25_2_8_None (25 floats)
    175, // dense_aaah_x1_1_25_p25_2_9_None (25 floats)
    200, // dense_aaai_x1_1_25_p25_2_10_None (25 floats)
    225, // dense_aaaj_x1_1_25_p25_2_11_None (25 floats)
    250, // dense_aaak_x1_1_50_p50_2_2_None (50 floats)
    300, // dense_aaal_x1_1_100_p100_2_2_None (100 floats)
    400, // dense_aaam_x1_1_150_p150_2_2_None (150 floats)
    550, // dense_aaan_x1_1_200_p200_2_2_None (200 floats)
    750, // dense_aaao_x1_1_250_p250_2_2_None (250 floats)
    1000, // dense_aaap_x1_1_300_p300_2_2_None (300 floats)
    1300, // dense_aaaq_x1_1_350_p350_2_2_None (350 floats)
    1650, // dense_aaar_x1_1_400_p400_2_2_None (400 floats)
    2050, // dense_aaas_x1_1_450_p450_2_2_None (450 floats)
    2500, // dense_aaat_x1_1_500_p500_2_2_None (500 floats)
    3000, // dense_aaau_x1_1_25_p25_1_2_None (25 floats)
    3025, // dense_aaav_x1_1_25_p25_5_2_None (25 floats)
    3050, // dense_aaaw_x1_1_25_p25_10_2_None (25 floats)
    3075, // dense_aaax_x1_1_25_p25_20_2_None (25 floats)
    3100, // dense_aaay_x1_1_25_p25_25_2_None (25 floats)
    3125, // dense_aaaz_x1_1_25_p25_30_2_None (25 floats)
    3150, // dense_aaba_x1_1_25_p25_35_2_None (25 floats)
    3175, // dense_aabb_x1_1_25_p25_40_2_None (25 floats)
    3200, // dense_aabc_x1_1_25_p25_45_2_None (25 floats)
    3225, // dense_aabd_x1_1_25_p25_50_2_None (25 floats)
    // --- Y (ground-truth outputs) ---
    3250, // dense_aaaa_x1_1_25_p25_2_2_None (2 floats)
    3252, // dense_aaab_x1_1_25_p25_2_3_None (2 floats)
    3254, // dense_aaac_x1_1_25_p25_2_4_None (2 floats)
    3256, // dense_aaad_x1_1_25_p25_2_5_None (2 floats)
    3258, // dense_aaae_x1_1_25_p25_2_6_None (2 floats)
    3260, // dense_aaaf_x1_1_25_p25_2_7_None (2 floats)
    3262, // dense_aaag_x1_1_25_p25_2_8_None (2 floats)
    3264, // dense_aaah_x1_1_25_p25_2_9_None (2 floats)
    3266, // dense_aaai_x1_1_25_p25_2_10_None (2 floats)
    3268, // dense_aaaj_x1_1_25_p25_2_11_None (2 floats)
    3270, // dense_aaak_x1_1_50_p50_2_2_None (2 floats)
    3272, // dense_aaal_x1_1_100_p100_2_2_None (2 floats)
    3274, // dense_aaam_x1_1_150_p150_2_2_None (2 floats)
    3276, // dense_aaan_x1_1_200_p200_2_2_None (2 floats)
    3278, // dense_aaao_x1_1_250_p250_2_2_None (2 floats)
    3280, // dense_aaap_x1_1_300_p300_2_2_None (2 floats)
    3282, // dense_aaaq_x1_1_350_p350_2_2_None (2 floats)
    3284, // dense_aaar_x1_1_400_p400_2_2_None (2 floats)
    3286, // dense_aaas_x1_1_450_p450_2_2_None (2 floats)
    3288, // dense_aaat_x1_1_500_p500_2_2_None (2 floats)
    3290, // dense_aaau_x1_1_25_p25_1_2_None (1 floats)
    3291, // dense_aaav_x1_1_25_p25_5_2_None (5 floats)
    3296, // dense_aaaw_x1_1_25_p25_10_2_None (10 floats)
    3306, // dense_aaax_x1_1_25_p25_20_2_None (20 floats)
    3326, // dense_aaay_x1_1_25_p25_25_2_None (25 floats)
    3351, // dense_aaaz_x1_1_25_p25_30_2_None (30 floats)
    3381, // dense_aaba_x1_1_25_p25_35_2_None (35 floats)
    3416, // dense_aabb_x1_1_25_p25_40_2_None (40 floats)
    3456, // dense_aabc_x1_1_25_p25_45_2_None (45 floats)
    3501, // dense_aabd_x1_1_25_p25_50_2_None (50 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // dense_aaaa_x1_1_25_p25_2_2_None
    25, // dense_aaab_x1_1_25_p25_2_3_None
    25, // dense_aaac_x1_1_25_p25_2_4_None
    25, // dense_aaad_x1_1_25_p25_2_5_None
    25, // dense_aaae_x1_1_25_p25_2_6_None
    25, // dense_aaaf_x1_1_25_p25_2_7_None
    25, // dense_aaag_x1_1_25_p25_2_8_None
    25, // dense_aaah_x1_1_25_p25_2_9_None
    25, // dense_aaai_x1_1_25_p25_2_10_None
    25, // dense_aaaj_x1_1_25_p25_2_11_None
    50, // dense_aaak_x1_1_50_p50_2_2_None
    100, // dense_aaal_x1_1_100_p100_2_2_None
    150, // dense_aaam_x1_1_150_p150_2_2_None
    200, // dense_aaan_x1_1_200_p200_2_2_None
    250, // dense_aaao_x1_1_250_p250_2_2_None
    300, // dense_aaap_x1_1_300_p300_2_2_None
    350, // dense_aaaq_x1_1_350_p350_2_2_None
    400, // dense_aaar_x1_1_400_p400_2_2_None
    450, // dense_aaas_x1_1_450_p450_2_2_None
    500, // dense_aaat_x1_1_500_p500_2_2_None
    25, // dense_aaau_x1_1_25_p25_1_2_None
    25, // dense_aaav_x1_1_25_p25_5_2_None
    25, // dense_aaaw_x1_1_25_p25_10_2_None
    25, // dense_aaax_x1_1_25_p25_20_2_None
    25, // dense_aaay_x1_1_25_p25_25_2_None
    25, // dense_aaaz_x1_1_25_p25_30_2_None
    25, // dense_aaba_x1_1_25_p25_35_2_None
    25, // dense_aabb_x1_1_25_p25_40_2_None
    25, // dense_aabc_x1_1_25_p25_45_2_None
    25, // dense_aabd_x1_1_25_p25_50_2_None
    // --- Y (ground-truth outputs) ---
    2, // dense_aaaa_x1_1_25_p25_2_2_None
    2, // dense_aaab_x1_1_25_p25_2_3_None
    2, // dense_aaac_x1_1_25_p25_2_4_None
    2, // dense_aaad_x1_1_25_p25_2_5_None
    2, // dense_aaae_x1_1_25_p25_2_6_None
    2, // dense_aaaf_x1_1_25_p25_2_7_None
    2, // dense_aaag_x1_1_25_p25_2_8_None
    2, // dense_aaah_x1_1_25_p25_2_9_None
    2, // dense_aaai_x1_1_25_p25_2_10_None
    2, // dense_aaaj_x1_1_25_p25_2_11_None
    2, // dense_aaak_x1_1_50_p50_2_2_None
    2, // dense_aaal_x1_1_100_p100_2_2_None
    2, // dense_aaam_x1_1_150_p150_2_2_None
    2, // dense_aaan_x1_1_200_p200_2_2_None
    2, // dense_aaao_x1_1_250_p250_2_2_None
    2, // dense_aaap_x1_1_300_p300_2_2_None
    2, // dense_aaaq_x1_1_350_p350_2_2_None
    2, // dense_aaar_x1_1_400_p400_2_2_None
    2, // dense_aaas_x1_1_450_p450_2_2_None
    2, // dense_aaat_x1_1_500_p500_2_2_None
    1, // dense_aaau_x1_1_25_p25_1_2_None
    5, // dense_aaav_x1_1_25_p25_5_2_None
    10, // dense_aaaw_x1_1_25_p25_10_2_None
    20, // dense_aaax_x1_1_25_p25_20_2_None
    25, // dense_aaay_x1_1_25_p25_25_2_None
    30, // dense_aaaz_x1_1_25_p25_30_2_None
    35, // dense_aaba_x1_1_25_p25_35_2_None
    40, // dense_aabb_x1_1_25_p25_40_2_None
    45, // dense_aabc_x1_1_25_p25_45_2_None
    50, // dense_aabd_x1_1_25_p25_50_2_None
};
