#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 1).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 8
#define X_TENSOR_COUNT 8
#define Y_TENSOR_COUNT 8
#define TENSOR_COUNT 16

static const uint32_t TOTAL_ELEMENTS = 52580; // floats in blob
static const uint32_t TOTAL_BYTES    = 210320; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 5100;
static const uint32_t Y_TOTAL_ELEMENTS = 47480;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_5_5_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    1, // conv_aaab_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    2, // conv_aaac_x1_15_15_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    3, // conv_aaad_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    4, // conv_aaae_x1_25_25_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    5, // conv_aaaf_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    6, // conv_aaag_x1_35_35_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    7, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_5_5_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    1, // conv_aaab_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    2, // conv_aaac_x1_15_15_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    3, // conv_aaad_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    4, // conv_aaae_x1_25_25_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    5, // conv_aaaf_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    6, // conv_aaag_x1_35_35_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    7, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // conv_aaaa_x1_5_5_p1_10_1_None_2_2_pool_2_2_1_1 (25 floats)
    25, // conv_aaab_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (100 floats)
    125, // conv_aaac_x1_15_15_p1_10_1_None_2_2_pool_2_2_1_1 (225 floats)
    350, // conv_aaad_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (400 floats)
    750, // conv_aaae_x1_25_25_p1_10_1_None_2_2_pool_2_2_1_1 (625 floats)
    1375, // conv_aaaf_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (900 floats)
    2275, // conv_aaag_x1_35_35_p1_10_1_None_2_2_pool_2_2_1_1 (1225 floats)
    3500, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1600 floats)
    // --- Y (ground-truth outputs) ---
    5100, // conv_aaaa_x1_5_5_p1_10_1_None_2_2_pool_2_2_1_1 (160 floats)
    5260, // conv_aaab_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (810 floats)
    6070, // conv_aaac_x1_15_15_p1_10_1_None_2_2_pool_2_2_1_1 (1960 floats)
    8030, // conv_aaad_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (3610 floats)
    11640, // conv_aaae_x1_25_25_p1_10_1_None_2_2_pool_2_2_1_1 (5760 floats)
    17400, // conv_aaaf_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (8410 floats)
    25810, // conv_aaag_x1_35_35_p1_10_1_None_2_2_pool_2_2_1_1 (11560 floats)
    37370, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (15210 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // conv_aaaa_x1_5_5_p1_10_1_None_2_2_pool_2_2_1_1
    100, // conv_aaab_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1
    225, // conv_aaac_x1_15_15_p1_10_1_None_2_2_pool_2_2_1_1
    400, // conv_aaad_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1
    625, // conv_aaae_x1_25_25_p1_10_1_None_2_2_pool_2_2_1_1
    900, // conv_aaaf_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1
    1225, // conv_aaag_x1_35_35_p1_10_1_None_2_2_pool_2_2_1_1
    1600, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1
    // --- Y (ground-truth outputs) ---
    160, // conv_aaaa_x1_5_5_p1_10_1_None_2_2_pool_2_2_1_1
    810, // conv_aaab_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1
    1960, // conv_aaac_x1_15_15_p1_10_1_None_2_2_pool_2_2_1_1
    3610, // conv_aaad_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1
    5760, // conv_aaae_x1_25_25_p1_10_1_None_2_2_pool_2_2_1_1
    8410, // conv_aaaf_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1
    11560, // conv_aaag_x1_35_35_p1_10_1_None_2_2_pool_2_2_1_1
    15210, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1
};
