#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 16
#define X_TENSOR_COUNT 16
#define Y_TENSOR_COUNT 16
#define TENSOR_COUNT 32

static const uint32_t TOTAL_ELEMENTS = 42826; // floats in blob
static const uint32_t TOTAL_BYTES    = 171304; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 4200;
static const uint32_t Y_TOTAL_ELEMENTS = 38626;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_2_50_p1_10_1_None_1_5_pool_1_2_1_1 (1 inputs)
    1, // conv_aaab_x1_2_50_p1_10_2_None_1_5_pool_1_2_1_1 (1 inputs)
    2, // conv_aaac_x1_2_50_p1_10_3_None_1_5_pool_1_2_1_1 (1 inputs)
    3, // conv_aaad_x1_2_50_p1_10_4_None_1_5_pool_1_2_1_1 (1 inputs)
    4, // conv_aaae_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    5, // conv_aaaf_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    6, // conv_aaag_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    7, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    8, // conv_aaai_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1 (1 inputs)
    9, // conv_aaaj_x1_1_100_p1_10_1_None_1_10_pool_1_2_1_1 (1 inputs)
    10, // conv_aaak_x1_1_100_p1_10_1_None_1_20_pool_1_2_1_1 (1 inputs)
    11, // conv_aaal_x1_1_100_p1_10_1_None_1_30_pool_1_2_1_1 (1 inputs)
    12, // conv_aaam_x1_1_100_p1_1_1_None_1_5_pool_1_2_1_1 (1 inputs)
    13, // conv_aaan_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1 (1 inputs)
    14, // conv_aaao_x1_1_100_p1_20_1_None_1_5_pool_1_2_1_1 (1 inputs)
    15, // conv_aaap_x1_1_100_p1_30_1_None_1_5_pool_1_2_1_1 (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_2_50_p1_10_1_None_1_5_pool_1_2_1_1 (1 outputs)
    1, // conv_aaab_x1_2_50_p1_10_2_None_1_5_pool_1_2_1_1 (1 outputs)
    2, // conv_aaac_x1_2_50_p1_10_3_None_1_5_pool_1_2_1_1 (1 outputs)
    3, // conv_aaad_x1_2_50_p1_10_4_None_1_5_pool_1_2_1_1 (1 outputs)
    4, // conv_aaae_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    5, // conv_aaaf_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    6, // conv_aaag_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    7, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    8, // conv_aaai_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1 (1 outputs)
    9, // conv_aaaj_x1_1_100_p1_10_1_None_1_10_pool_1_2_1_1 (1 outputs)
    10, // conv_aaak_x1_1_100_p1_10_1_None_1_20_pool_1_2_1_1 (1 outputs)
    11, // conv_aaal_x1_1_100_p1_10_1_None_1_30_pool_1_2_1_1 (1 outputs)
    12, // conv_aaam_x1_1_100_p1_1_1_None_1_5_pool_1_2_1_1 (1 outputs)
    13, // conv_aaan_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1 (1 outputs)
    14, // conv_aaao_x1_1_100_p1_20_1_None_1_5_pool_1_2_1_1 (1 outputs)
    15, // conv_aaap_x1_1_100_p1_30_1_None_1_5_pool_1_2_1_1 (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // conv_aaaa_x1_2_50_p1_10_1_None_1_5_pool_1_2_1_1 (100 floats)
    100, // conv_aaab_x1_2_50_p1_10_2_None_1_5_pool_1_2_1_1 (100 floats)
    200, // conv_aaac_x1_2_50_p1_10_3_None_1_5_pool_1_2_1_1 (100 floats)
    300, // conv_aaad_x1_2_50_p1_10_4_None_1_5_pool_1_2_1_1 (100 floats)
    400, // conv_aaae_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (100 floats)
    500, // conv_aaaf_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (400 floats)
    900, // conv_aaag_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (900 floats)
    1800, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1600 floats)
    3400, // conv_aaai_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1 (100 floats)
    3500, // conv_aaaj_x1_1_100_p1_10_1_None_1_10_pool_1_2_1_1 (100 floats)
    3600, // conv_aaak_x1_1_100_p1_10_1_None_1_20_pool_1_2_1_1 (100 floats)
    3700, // conv_aaal_x1_1_100_p1_10_1_None_1_30_pool_1_2_1_1 (100 floats)
    3800, // conv_aaam_x1_1_100_p1_1_1_None_1_5_pool_1_2_1_1 (100 floats)
    3900, // conv_aaan_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1 (100 floats)
    4000, // conv_aaao_x1_1_100_p1_20_1_None_1_5_pool_1_2_1_1 (100 floats)
    4100, // conv_aaap_x1_1_100_p1_30_1_None_1_5_pool_1_2_1_1 (100 floats)
    // --- Y (ground-truth outputs) ---
    4200, // conv_aaaa_x1_2_50_p1_10_1_None_1_5_pool_1_2_1_1 (920 floats)
    5120, // conv_aaab_x1_2_50_p1_10_2_None_1_5_pool_1_2_1_1 (240 floats)
    5360, // conv_aaac_x1_2_50_p1_10_3_None_1_5_pool_1_2_1_1 (120 floats)
    5480, // conv_aaad_x1_2_50_p1_10_4_None_1_5_pool_1_2_1_1 (60 floats)
    5540, // conv_aaae_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (810 floats)
    6350, // conv_aaaf_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (3610 floats)
    9960, // conv_aaag_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (8410 floats)
    18370, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (15210 floats)
    33580, // conv_aaai_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1 (960 floats)
    34540, // conv_aaaj_x1_1_100_p1_10_1_None_1_10_pool_1_2_1_1 (910 floats)
    35450, // conv_aaak_x1_1_100_p1_10_1_None_1_20_pool_1_2_1_1 (810 floats)
    36260, // conv_aaal_x1_1_100_p1_10_1_None_1_30_pool_1_2_1_1 (710 floats)
    36970, // conv_aaam_x1_1_100_p1_1_1_None_1_5_pool_1_2_1_1 (96 floats)
    37066, // conv_aaan_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1 (960 floats)
    38026, // conv_aaao_x1_1_100_p1_20_1_None_1_5_pool_1_2_1_1 (1920 floats)
    39946, // conv_aaap_x1_1_100_p1_30_1_None_1_5_pool_1_2_1_1 (2880 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    100, // conv_aaaa_x1_2_50_p1_10_1_None_1_5_pool_1_2_1_1
    100, // conv_aaab_x1_2_50_p1_10_2_None_1_5_pool_1_2_1_1
    100, // conv_aaac_x1_2_50_p1_10_3_None_1_5_pool_1_2_1_1
    100, // conv_aaad_x1_2_50_p1_10_4_None_1_5_pool_1_2_1_1
    100, // conv_aaae_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1
    400, // conv_aaaf_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1
    900, // conv_aaag_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1
    1600, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1
    100, // conv_aaai_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1
    100, // conv_aaaj_x1_1_100_p1_10_1_None_1_10_pool_1_2_1_1
    100, // conv_aaak_x1_1_100_p1_10_1_None_1_20_pool_1_2_1_1
    100, // conv_aaal_x1_1_100_p1_10_1_None_1_30_pool_1_2_1_1
    100, // conv_aaam_x1_1_100_p1_1_1_None_1_5_pool_1_2_1_1
    100, // conv_aaan_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1
    100, // conv_aaao_x1_1_100_p1_20_1_None_1_5_pool_1_2_1_1
    100, // conv_aaap_x1_1_100_p1_30_1_None_1_5_pool_1_2_1_1
    // --- Y (ground-truth outputs) ---
    920, // conv_aaaa_x1_2_50_p1_10_1_None_1_5_pool_1_2_1_1
    240, // conv_aaab_x1_2_50_p1_10_2_None_1_5_pool_1_2_1_1
    120, // conv_aaac_x1_2_50_p1_10_3_None_1_5_pool_1_2_1_1
    60, // conv_aaad_x1_2_50_p1_10_4_None_1_5_pool_1_2_1_1
    810, // conv_aaae_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1
    3610, // conv_aaaf_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1
    8410, // conv_aaag_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1
    15210, // conv_aaah_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1
    960, // conv_aaai_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1
    910, // conv_aaaj_x1_1_100_p1_10_1_None_1_10_pool_1_2_1_1
    810, // conv_aaak_x1_1_100_p1_10_1_None_1_20_pool_1_2_1_1
    710, // conv_aaal_x1_1_100_p1_10_1_None_1_30_pool_1_2_1_1
    96, // conv_aaam_x1_1_100_p1_1_1_None_1_5_pool_1_2_1_1
    960, // conv_aaan_x1_1_100_p1_10_1_None_1_5_pool_1_2_1_1
    1920, // conv_aaao_x1_1_100_p1_20_1_None_1_5_pool_1_2_1_1
    2880, // conv_aaap_x1_1_100_p1_30_1_None_1_5_pool_1_2_1_1
};
