#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 0).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 5
#define X_TENSOR_COUNT 15
#define Y_TENSOR_COUNT 15
#define TENSOR_COUNT 30

static const uint32_t TOTAL_ELEMENTS = 3050; // floats in blob
static const uint32_t TOTAL_BYTES    = 12200; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 1525;
static const uint32_t Y_TOTAL_ELEMENTS = 1525;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_1 (3 inputs)
    3, // lstm_aaab_x5_1_25_p25_25_1 (3 inputs)
    6, // lstm_aaac_x10_1_25_p25_25_1 (3 inputs)
    9, // lstm_aaad_x15_1_25_p25_25_1 (3 inputs)
    12, // lstm_aaae_x20_1_25_p25_25_1 (3 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_1 (3 outputs)
    3, // lstm_aaab_x5_1_25_p25_25_1 (3 outputs)
    6, // lstm_aaac_x10_1_25_p25_25_1 (3 outputs)
    9, // lstm_aaad_x15_1_25_p25_25_1 (3 outputs)
    12, // lstm_aaae_x20_1_25_p25_25_1 (3 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    25, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    50, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    75, // lstm_aaab_x5_1_25_p25_25_1 (125 floats)
    200, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    225, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    250, // lstm_aaac_x10_1_25_p25_25_1 (250 floats)
    500, // lstm_aaac_x10_1_25_p25_25_1 (25 floats)
    525, // lstm_aaac_x10_1_25_p25_25_1 (25 floats)
    550, // lstm_aaad_x15_1_25_p25_25_1 (375 floats)
    925, // lstm_aaad_x15_1_25_p25_25_1 (25 floats)
    950, // lstm_aaad_x15_1_25_p25_25_1 (25 floats)
    975, // lstm_aaae_x20_1_25_p25_25_1 (500 floats)
    1475, // lstm_aaae_x20_1_25_p25_25_1 (25 floats)
    1500, // lstm_aaae_x20_1_25_p25_25_1 (25 floats)
    // --- Y (ground-truth outputs) ---
    1525, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    1550, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    1575, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    1600, // lstm_aaab_x5_1_25_p25_25_1 (125 floats)
    1725, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    1750, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    1775, // lstm_aaac_x10_1_25_p25_25_1 (250 floats)
    2025, // lstm_aaac_x10_1_25_p25_25_1 (25 floats)
    2050, // lstm_aaac_x10_1_25_p25_25_1 (25 floats)
    2075, // lstm_aaad_x15_1_25_p25_25_1 (375 floats)
    2450, // lstm_aaad_x15_1_25_p25_25_1 (25 floats)
    2475, // lstm_aaad_x15_1_25_p25_25_1 (25 floats)
    2500, // lstm_aaae_x20_1_25_p25_25_1 (500 floats)
    3000, // lstm_aaae_x20_1_25_p25_25_1 (25 floats)
    3025, // lstm_aaae_x20_1_25_p25_25_1 (25 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    125, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    250, // lstm_aaac_x10_1_25_p25_25_1
    25, // lstm_aaac_x10_1_25_p25_25_1
    25, // lstm_aaac_x10_1_25_p25_25_1
    375, // lstm_aaad_x15_1_25_p25_25_1
    25, // lstm_aaad_x15_1_25_p25_25_1
    25, // lstm_aaad_x15_1_25_p25_25_1
    500, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaae_x20_1_25_p25_25_1
    // --- Y (ground-truth outputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    125, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    250, // lstm_aaac_x10_1_25_p25_25_1
    25, // lstm_aaac_x10_1_25_p25_25_1
    25, // lstm_aaac_x10_1_25_p25_25_1
    375, // lstm_aaad_x15_1_25_p25_25_1
    25, // lstm_aaad_x15_1_25_p25_25_1
    25, // lstm_aaad_x15_1_25_p25_25_1
    500, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaae_x20_1_25_p25_25_1
};
