#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 0).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 4
#define X_TENSOR_COUNT 12
#define Y_TENSOR_COUNT 12
#define TENSOR_COUNT 24

static const uint32_t TOTAL_ELEMENTS = 3000; // floats in blob
static const uint32_t TOTAL_BYTES    = 12000; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 1500;
static const uint32_t Y_TOTAL_ELEMENTS = 1500;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_50_p50_50_1 (3 inputs)
    3, // lstm_aaab_x1_1_100_p100_100_1 (3 inputs)
    6, // lstm_aaac_x1_1_150_p150_150_1 (3 inputs)
    9, // lstm_aaad_x1_1_200_p200_200_1 (3 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_50_p50_50_1 (3 outputs)
    3, // lstm_aaab_x1_1_100_p100_100_1 (3 outputs)
    6, // lstm_aaac_x1_1_150_p150_150_1 (3 outputs)
    9, // lstm_aaad_x1_1_200_p200_200_1 (3 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // lstm_aaaa_x1_1_50_p50_50_1 (50 floats)
    50, // lstm_aaaa_x1_1_50_p50_50_1 (50 floats)
    100, // lstm_aaaa_x1_1_50_p50_50_1 (50 floats)
    150, // lstm_aaab_x1_1_100_p100_100_1 (100 floats)
    250, // lstm_aaab_x1_1_100_p100_100_1 (100 floats)
    350, // lstm_aaab_x1_1_100_p100_100_1 (100 floats)
    450, // lstm_aaac_x1_1_150_p150_150_1 (150 floats)
    600, // lstm_aaac_x1_1_150_p150_150_1 (150 floats)
    750, // lstm_aaac_x1_1_150_p150_150_1 (150 floats)
    900, // lstm_aaad_x1_1_200_p200_200_1 (200 floats)
    1100, // lstm_aaad_x1_1_200_p200_200_1 (200 floats)
    1300, // lstm_aaad_x1_1_200_p200_200_1 (200 floats)
    // --- Y (ground-truth outputs) ---
    1500, // lstm_aaaa_x1_1_50_p50_50_1 (50 floats)
    1550, // lstm_aaaa_x1_1_50_p50_50_1 (50 floats)
    1600, // lstm_aaaa_x1_1_50_p50_50_1 (50 floats)
    1650, // lstm_aaab_x1_1_100_p100_100_1 (100 floats)
    1750, // lstm_aaab_x1_1_100_p100_100_1 (100 floats)
    1850, // lstm_aaab_x1_1_100_p100_100_1 (100 floats)
    1950, // lstm_aaac_x1_1_150_p150_150_1 (150 floats)
    2100, // lstm_aaac_x1_1_150_p150_150_1 (150 floats)
    2250, // lstm_aaac_x1_1_150_p150_150_1 (150 floats)
    2400, // lstm_aaad_x1_1_200_p200_200_1 (200 floats)
    2600, // lstm_aaad_x1_1_200_p200_200_1 (200 floats)
    2800, // lstm_aaad_x1_1_200_p200_200_1 (200 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    50, // lstm_aaaa_x1_1_50_p50_50_1
    50, // lstm_aaaa_x1_1_50_p50_50_1
    50, // lstm_aaaa_x1_1_50_p50_50_1
    100, // lstm_aaab_x1_1_100_p100_100_1
    100, // lstm_aaab_x1_1_100_p100_100_1
    100, // lstm_aaab_x1_1_100_p100_100_1
    150, // lstm_aaac_x1_1_150_p150_150_1
    150, // lstm_aaac_x1_1_150_p150_150_1
    150, // lstm_aaac_x1_1_150_p150_150_1
    200, // lstm_aaad_x1_1_200_p200_200_1
    200, // lstm_aaad_x1_1_200_p200_200_1
    200, // lstm_aaad_x1_1_200_p200_200_1
    // --- Y (ground-truth outputs) ---
    50, // lstm_aaaa_x1_1_50_p50_50_1
    50, // lstm_aaaa_x1_1_50_p50_50_1
    50, // lstm_aaaa_x1_1_50_p50_50_1
    100, // lstm_aaab_x1_1_100_p100_100_1
    100, // lstm_aaab_x1_1_100_p100_100_1
    100, // lstm_aaab_x1_1_100_p100_100_1
    150, // lstm_aaac_x1_1_150_p150_150_1
    150, // lstm_aaac_x1_1_150_p150_150_1
    150, // lstm_aaac_x1_1_150_p150_150_1
    200, // lstm_aaad_x1_1_200_p200_200_1
    200, // lstm_aaad_x1_1_200_p200_200_1
    200, // lstm_aaad_x1_1_200_p200_200_1
};
