#pragma once
#include <stdint.h>

// Auto-generated by export_bin_manifest_multitrial.py -- do not edit.
// Single config (0), 20 trials (every 10th of 192).

#define DATA_TRIAL_COUNT 20
#define DATA_CONFIG_INDEX 0
#define FEATURE_CHANNELS 56
#define DATA_OUTPUT_CHANNELS 2

#define X_REGION_BYTE_OFFSET 0u
#define Y_REGION_BYTE_OFFSET 5760000u
#define DATA_BIN_TOTAL_BYTES 6480000u

#define MAIN_WINDOW_LEN 500u
#define MAIN_STEP 1u
#define MAIN_OUT_LEN 250u
#define MAIN_INTERMEDIATE_SIZE 56u

// Original test-set trial indices, in trial-slot order.
// Lets the device CSV report the true trial id, not just 0..N-1.
static const uint32_t MAIN_TRIAL_IDS[20] = { 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190 };

// Per-trial float-index offsets; last entry = total floats in region
static const uint32_t MAIN_X_OFFSETS[21] = { 0, 72000, 144000, 216000, 288000, 360000, 432000, 504000, 576000, 648000, 720000, 792000, 864000, 936000, 1008000, 1080000, 1152000, 1224000, 1296000, 1368000, 1440000 };
static const uint32_t MAIN_X_SIZES[20] = { 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000, 72000 };
static const uint32_t MAIN_Y_OFFSETS[21] = { 0, 9000, 18000, 27000, 36000, 45000, 54000, 63000, 72000, 81000, 90000, 99000, 108000, 117000, 126000, 135000, 144000, 153000, 162000, 171000, 180000 };
static const uint32_t MAIN_Y_SIZES[20] = { 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000 };
