/**
 * scaler_params.h
 * Auto-generated by generate_scaler_header.py
 * DO NOT EDIT MANUALLY.
 *
 * Apply BEFORE feeding sensor data into the model:
 *   normalized = (raw - FEATURE_MEAN[i]) / FEATURE_SCALE[i]
 *
 * Apply AFTER reading Euler output from the model:
 *   degrees = normalized * EULER_SCALE[i] + EULER_MEAN[i]
 *
 * Feature column order:
 *   [0] Gyro_x
 *   [1] Gyro_y
 *   [2] Gyro_z
 *   [3] Acc_x
 *   [4] Acc_y
 *   [5] Acc_z
 *   [6] Mag_x
 *   [7] Mag_y
 *   [8] Mag_z
 */

#pragma once
#include <stdint.h>

// Number of input sensor channels (must match model input features)
constexpr int NUM_FEATURES = 9;

// Number of Euler angle outputs
constexpr int NUM_EULER = 3;

// ---- Feature normalization (StandardScaler) ----
// normalized_feature[i] = (raw[i] - FEATURE_MEAN[i]) / FEATURE_SCALE[i]
constexpr float FEATURE_MEAN[9] = {
    -17.4656734099f,
    -3.9559399718f,
    6.6234614587f,
    0.0816314415f,
    2.7872580009f,
    1.9232381137f,
    0.1807451389f,
    0.9723708333f,
    -2.6877444444f
};

constexpr float FEATURE_SCALE[9] = {
    197.3328127315f,
    168.6774005332f,
    208.6449753536f,
    9.4821666489f,
    6.7507290505f,
    9.4950174257f,
    17.6406706902f,
    19.1232048744f,
    19.6787863219f
};

// ---- Euler angle denormalization (inverse StandardScaler) ----
// euler_degrees[i] = model_output[i] * EULER_SCALE[i] + EULER_MEAN[i]
constexpr float EULER_MEAN[3] = {
    2.0897550569f,
    -2.1171333333f,
    178.8287378638f
};

constexpr float EULER_SCALE[3] = {
    98.2619747211f,
    39.5549072933f,
    105.9246515141f
};

// // ---- Inline helper: normalize one feature vector in-place ----
// // Call this on raw sensor readings before passing to Model::predict()
// inline void normalize_features(float* features, int n) {
//     for (int i = 0; i < n && i < NUM_FEATURES; i++) {
//         features[i] = (features[i] - FEATURE_MEAN[i]) / FEATURE_SCALE[i];
//     }
// }

// // ---- Inline helper: denormalize Euler angles in-place ----
// // Call this on the first NUM_EULER elements of Model::predict() output
// inline void denormalize_euler(float* euler, int n) {
//     for (int i = 0; i < n && i < NUM_EULER; i++) {
//         euler[i] = euler[i] * EULER_SCALE[i] + EULER_MEAN[i];
//     }
// }
