#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 16
#define X_TENSOR_COUNT 48
#define Y_TENSOR_COUNT 48
#define TENSOR_COUNT 96

static const uint32_t TOTAL_ELEMENTS = 8600; // floats in blob
static const uint32_t TOTAL_BYTES    = 34400; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 4300;
static const uint32_t Y_TOTAL_ELEMENTS = 4300;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_1 (3 inputs)
    3, // lstm_aaab_x5_1_25_p25_25_1 (3 inputs)
    6, // lstm_aaac_x10_1_25_p25_25_1 (3 inputs)
    9, // lstm_aaad_x15_1_25_p25_25_1 (3 inputs)
    12, // lstm_aaae_x20_1_25_p25_25_1 (3 inputs)
    15, // lstm_aaaf_x1_1_25_p25_25_1 (3 inputs)
    18, // lstm_aaag_x1_1_50_p50_50_1 (3 inputs)
    21, // lstm_aaah_x1_1_100_p100_100_1 (3 inputs)
    24, // lstm_aaai_x1_1_150_p150_150_1 (3 inputs)
    27, // lstm_aaaj_x1_1_200_p200_200_1 (3 inputs)
    30, // lstm_aaak_x1_1_25_p25_25_1 (3 inputs)
    33, // lstm_aaal_x1_1_25_p25_25_2 (3 inputs)
    36, // lstm_aaam_x1_1_25_p25_25_3 (3 inputs)
    39, // lstm_aaan_x1_1_25_p25_25_4 (3 inputs)
    42, // lstm_aaao_x1_1_25_p25_25_5 (3 inputs)
    45, // lstm_aaap_x1_1_25_p25_25_6 (3 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_1 (3 outputs)
    3, // lstm_aaab_x5_1_25_p25_25_1 (3 outputs)
    6, // lstm_aaac_x10_1_25_p25_25_1 (3 outputs)
    9, // lstm_aaad_x15_1_25_p25_25_1 (3 outputs)
    12, // lstm_aaae_x20_1_25_p25_25_1 (3 outputs)
    15, // lstm_aaaf_x1_1_25_p25_25_1 (3 outputs)
    18, // lstm_aaag_x1_1_50_p50_50_1 (3 outputs)
    21, // lstm_aaah_x1_1_100_p100_100_1 (3 outputs)
    24, // lstm_aaai_x1_1_150_p150_150_1 (3 outputs)
    27, // lstm_aaaj_x1_1_200_p200_200_1 (3 outputs)
    30, // lstm_aaak_x1_1_25_p25_25_1 (3 outputs)
    33, // lstm_aaal_x1_1_25_p25_25_2 (3 outputs)
    36, // lstm_aaam_x1_1_25_p25_25_3 (3 outputs)
    39, // lstm_aaan_x1_1_25_p25_25_4 (3 outputs)
    42, // lstm_aaao_x1_1_25_p25_25_5 (3 outputs)
    45, // lstm_aaap_x1_1_25_p25_25_6 (3 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    25, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    50, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    75, // lstm_aaab_x5_1_25_p25_25_1 (125 floats)
    200, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    225, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    250, // lstm_aaac_x10_1_25_p25_25_1 (250 floats)
    500, // lstm_aaac_x10_1_25_p25_25_1 (25 floats)
    525, // lstm_aaac_x10_1_25_p25_25_1 (25 floats)
    550, // lstm_aaad_x15_1_25_p25_25_1 (375 floats)
    925, // lstm_aaad_x15_1_25_p25_25_1 (25 floats)
    950, // lstm_aaad_x15_1_25_p25_25_1 (25 floats)
    975, // lstm_aaae_x20_1_25_p25_25_1 (500 floats)
    1475, // lstm_aaae_x20_1_25_p25_25_1 (25 floats)
    1500, // lstm_aaae_x20_1_25_p25_25_1 (25 floats)
    1525, // lstm_aaaf_x1_1_25_p25_25_1 (25 floats)
    1550, // lstm_aaaf_x1_1_25_p25_25_1 (25 floats)
    1575, // lstm_aaaf_x1_1_25_p25_25_1 (25 floats)
    1600, // lstm_aaag_x1_1_50_p50_50_1 (50 floats)
    1650, // lstm_aaag_x1_1_50_p50_50_1 (50 floats)
    1700, // lstm_aaag_x1_1_50_p50_50_1 (50 floats)
    1750, // lstm_aaah_x1_1_100_p100_100_1 (100 floats)
    1850, // lstm_aaah_x1_1_100_p100_100_1 (100 floats)
    1950, // lstm_aaah_x1_1_100_p100_100_1 (100 floats)
    2050, // lstm_aaai_x1_1_150_p150_150_1 (150 floats)
    2200, // lstm_aaai_x1_1_150_p150_150_1 (150 floats)
    2350, // lstm_aaai_x1_1_150_p150_150_1 (150 floats)
    2500, // lstm_aaaj_x1_1_200_p200_200_1 (200 floats)
    2700, // lstm_aaaj_x1_1_200_p200_200_1 (200 floats)
    2900, // lstm_aaaj_x1_1_200_p200_200_1 (200 floats)
    3100, // lstm_aaak_x1_1_25_p25_25_1 (25 floats)
    3125, // lstm_aaak_x1_1_25_p25_25_1 (25 floats)
    3150, // lstm_aaak_x1_1_25_p25_25_1 (25 floats)
    3175, // lstm_aaal_x1_1_25_p25_25_2 (25 floats)
    3200, // lstm_aaal_x1_1_25_p25_25_2 (50 floats)
    3250, // lstm_aaal_x1_1_25_p25_25_2 (50 floats)
    3300, // lstm_aaam_x1_1_25_p25_25_3 (25 floats)
    3325, // lstm_aaam_x1_1_25_p25_25_3 (75 floats)
    3400, // lstm_aaam_x1_1_25_p25_25_3 (75 floats)
    3475, // lstm_aaan_x1_1_25_p25_25_4 (25 floats)
    3500, // lstm_aaan_x1_1_25_p25_25_4 (100 floats)
    3600, // lstm_aaan_x1_1_25_p25_25_4 (100 floats)
    3700, // lstm_aaao_x1_1_25_p25_25_5 (25 floats)
    3725, // lstm_aaao_x1_1_25_p25_25_5 (125 floats)
    3850, // lstm_aaao_x1_1_25_p25_25_5 (125 floats)
    3975, // lstm_aaap_x1_1_25_p25_25_6 (25 floats)
    4000, // lstm_aaap_x1_1_25_p25_25_6 (150 floats)
    4150, // lstm_aaap_x1_1_25_p25_25_6 (150 floats)
    // --- Y (ground-truth outputs) ---
    4300, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    4325, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    4350, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    4375, // lstm_aaab_x5_1_25_p25_25_1 (125 floats)
    4500, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    4525, // lstm_aaab_x5_1_25_p25_25_1 (25 floats)
    4550, // lstm_aaac_x10_1_25_p25_25_1 (250 floats)
    4800, // lstm_aaac_x10_1_25_p25_25_1 (25 floats)
    4825, // lstm_aaac_x10_1_25_p25_25_1 (25 floats)
    4850, // lstm_aaad_x15_1_25_p25_25_1 (375 floats)
    5225, // lstm_aaad_x15_1_25_p25_25_1 (25 floats)
    5250, // lstm_aaad_x15_1_25_p25_25_1 (25 floats)
    5275, // lstm_aaae_x20_1_25_p25_25_1 (500 floats)
    5775, // lstm_aaae_x20_1_25_p25_25_1 (25 floats)
    5800, // lstm_aaae_x20_1_25_p25_25_1 (25 floats)
    5825, // lstm_aaaf_x1_1_25_p25_25_1 (25 floats)
    5850, // lstm_aaaf_x1_1_25_p25_25_1 (25 floats)
    5875, // lstm_aaaf_x1_1_25_p25_25_1 (25 floats)
    5900, // lstm_aaag_x1_1_50_p50_50_1 (50 floats)
    5950, // lstm_aaag_x1_1_50_p50_50_1 (50 floats)
    6000, // lstm_aaag_x1_1_50_p50_50_1 (50 floats)
    6050, // lstm_aaah_x1_1_100_p100_100_1 (100 floats)
    6150, // lstm_aaah_x1_1_100_p100_100_1 (100 floats)
    6250, // lstm_aaah_x1_1_100_p100_100_1 (100 floats)
    6350, // lstm_aaai_x1_1_150_p150_150_1 (150 floats)
    6500, // lstm_aaai_x1_1_150_p150_150_1 (150 floats)
    6650, // lstm_aaai_x1_1_150_p150_150_1 (150 floats)
    6800, // lstm_aaaj_x1_1_200_p200_200_1 (200 floats)
    7000, // lstm_aaaj_x1_1_200_p200_200_1 (200 floats)
    7200, // lstm_aaaj_x1_1_200_p200_200_1 (200 floats)
    7400, // lstm_aaak_x1_1_25_p25_25_1 (25 floats)
    7425, // lstm_aaak_x1_1_25_p25_25_1 (25 floats)
    7450, // lstm_aaak_x1_1_25_p25_25_1 (25 floats)
    7475, // lstm_aaal_x1_1_25_p25_25_2 (25 floats)
    7500, // lstm_aaal_x1_1_25_p25_25_2 (50 floats)
    7550, // lstm_aaal_x1_1_25_p25_25_2 (50 floats)
    7600, // lstm_aaam_x1_1_25_p25_25_3 (25 floats)
    7625, // lstm_aaam_x1_1_25_p25_25_3 (75 floats)
    7700, // lstm_aaam_x1_1_25_p25_25_3 (75 floats)
    7775, // lstm_aaan_x1_1_25_p25_25_4 (25 floats)
    7800, // lstm_aaan_x1_1_25_p25_25_4 (100 floats)
    7900, // lstm_aaan_x1_1_25_p25_25_4 (100 floats)
    8000, // lstm_aaao_x1_1_25_p25_25_5 (25 floats)
    8025, // lstm_aaao_x1_1_25_p25_25_5 (125 floats)
    8150, // lstm_aaao_x1_1_25_p25_25_5 (125 floats)
    8275, // lstm_aaap_x1_1_25_p25_25_6 (25 floats)
    8300, // lstm_aaap_x1_1_25_p25_25_6 (150 floats)
    8450, // lstm_aaap_x1_1_25_p25_25_6 (150 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    125, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    250, // lstm_aaac_x10_1_25_p25_25_1
    25, // lstm_aaac_x10_1_25_p25_25_1
    25, // lstm_aaac_x10_1_25_p25_25_1
    375, // lstm_aaad_x15_1_25_p25_25_1
    25, // lstm_aaad_x15_1_25_p25_25_1
    25, // lstm_aaad_x15_1_25_p25_25_1
    500, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaaf_x1_1_25_p25_25_1
    25, // lstm_aaaf_x1_1_25_p25_25_1
    25, // lstm_aaaf_x1_1_25_p25_25_1
    50, // lstm_aaag_x1_1_50_p50_50_1
    50, // lstm_aaag_x1_1_50_p50_50_1
    50, // lstm_aaag_x1_1_50_p50_50_1
    100, // lstm_aaah_x1_1_100_p100_100_1
    100, // lstm_aaah_x1_1_100_p100_100_1
    100, // lstm_aaah_x1_1_100_p100_100_1
    150, // lstm_aaai_x1_1_150_p150_150_1
    150, // lstm_aaai_x1_1_150_p150_150_1
    150, // lstm_aaai_x1_1_150_p150_150_1
    200, // lstm_aaaj_x1_1_200_p200_200_1
    200, // lstm_aaaj_x1_1_200_p200_200_1
    200, // lstm_aaaj_x1_1_200_p200_200_1
    25, // lstm_aaak_x1_1_25_p25_25_1
    25, // lstm_aaak_x1_1_25_p25_25_1
    25, // lstm_aaak_x1_1_25_p25_25_1
    25, // lstm_aaal_x1_1_25_p25_25_2
    50, // lstm_aaal_x1_1_25_p25_25_2
    50, // lstm_aaal_x1_1_25_p25_25_2
    25, // lstm_aaam_x1_1_25_p25_25_3
    75, // lstm_aaam_x1_1_25_p25_25_3
    75, // lstm_aaam_x1_1_25_p25_25_3
    25, // lstm_aaan_x1_1_25_p25_25_4
    100, // lstm_aaan_x1_1_25_p25_25_4
    100, // lstm_aaan_x1_1_25_p25_25_4
    25, // lstm_aaao_x1_1_25_p25_25_5
    125, // lstm_aaao_x1_1_25_p25_25_5
    125, // lstm_aaao_x1_1_25_p25_25_5
    25, // lstm_aaap_x1_1_25_p25_25_6
    150, // lstm_aaap_x1_1_25_p25_25_6
    150, // lstm_aaap_x1_1_25_p25_25_6
    // --- Y (ground-truth outputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    125, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    25, // lstm_aaab_x5_1_25_p25_25_1
    250, // lstm_aaac_x10_1_25_p25_25_1
    25, // lstm_aaac_x10_1_25_p25_25_1
    25, // lstm_aaac_x10_1_25_p25_25_1
    375, // lstm_aaad_x15_1_25_p25_25_1
    25, // lstm_aaad_x15_1_25_p25_25_1
    25, // lstm_aaad_x15_1_25_p25_25_1
    500, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaae_x20_1_25_p25_25_1
    25, // lstm_aaaf_x1_1_25_p25_25_1
    25, // lstm_aaaf_x1_1_25_p25_25_1
    25, // lstm_aaaf_x1_1_25_p25_25_1
    50, // lstm_aaag_x1_1_50_p50_50_1
    50, // lstm_aaag_x1_1_50_p50_50_1
    50, // lstm_aaag_x1_1_50_p50_50_1
    100, // lstm_aaah_x1_1_100_p100_100_1
    100, // lstm_aaah_x1_1_100_p100_100_1
    100, // lstm_aaah_x1_1_100_p100_100_1
    150, // lstm_aaai_x1_1_150_p150_150_1
    150, // lstm_aaai_x1_1_150_p150_150_1
    150, // lstm_aaai_x1_1_150_p150_150_1
    200, // lstm_aaaj_x1_1_200_p200_200_1
    200, // lstm_aaaj_x1_1_200_p200_200_1
    200, // lstm_aaaj_x1_1_200_p200_200_1
    25, // lstm_aaak_x1_1_25_p25_25_1
    25, // lstm_aaak_x1_1_25_p25_25_1
    25, // lstm_aaak_x1_1_25_p25_25_1
    25, // lstm_aaal_x1_1_25_p25_25_2
    50, // lstm_aaal_x1_1_25_p25_25_2
    50, // lstm_aaal_x1_1_25_p25_25_2
    25, // lstm_aaam_x1_1_25_p25_25_3
    75, // lstm_aaam_x1_1_25_p25_25_3
    75, // lstm_aaam_x1_1_25_p25_25_3
    25, // lstm_aaan_x1_1_25_p25_25_4
    100, // lstm_aaan_x1_1_25_p25_25_4
    100, // lstm_aaan_x1_1_25_p25_25_4
    25, // lstm_aaao_x1_1_25_p25_25_5
    125, // lstm_aaao_x1_1_25_p25_25_5
    125, // lstm_aaao_x1_1_25_p25_25_5
    25, // lstm_aaap_x1_1_25_p25_25_6
    150, // lstm_aaap_x1_1_25_p25_25_6
    150, // lstm_aaap_x1_1_25_p25_25_6
};
