#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 0).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 5
#define X_TENSOR_COUNT 15
#define Y_TENSOR_COUNT 15
#define TENSOR_COUNT 30

static const uint32_t TOTAL_ELEMENTS = 2250; // floats in blob
static const uint32_t TOTAL_BYTES    = 9000; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 1125;
static const uint32_t Y_TOTAL_ELEMENTS = 1125;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_2 (3 inputs)
    3, // lstm_aaab_x1_1_25_p25_25_3 (3 inputs)
    6, // lstm_aaac_x1_1_25_p25_25_4 (3 inputs)
    9, // lstm_aaad_x1_1_25_p25_25_5 (3 inputs)
    12, // lstm_aaae_x1_1_25_p25_25_6 (3 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_2 (3 outputs)
    3, // lstm_aaab_x1_1_25_p25_25_3 (3 outputs)
    6, // lstm_aaac_x1_1_25_p25_25_4 (3 outputs)
    9, // lstm_aaad_x1_1_25_p25_25_5 (3 outputs)
    12, // lstm_aaae_x1_1_25_p25_25_6 (3 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // lstm_aaaa_x1_1_25_p25_25_2 (25 floats)
    25, // lstm_aaaa_x1_1_25_p25_25_2 (50 floats)
    75, // lstm_aaaa_x1_1_25_p25_25_2 (50 floats)
    125, // lstm_aaab_x1_1_25_p25_25_3 (25 floats)
    150, // lstm_aaab_x1_1_25_p25_25_3 (75 floats)
    225, // lstm_aaab_x1_1_25_p25_25_3 (75 floats)
    300, // lstm_aaac_x1_1_25_p25_25_4 (25 floats)
    325, // lstm_aaac_x1_1_25_p25_25_4 (100 floats)
    425, // lstm_aaac_x1_1_25_p25_25_4 (100 floats)
    525, // lstm_aaad_x1_1_25_p25_25_5 (25 floats)
    550, // lstm_aaad_x1_1_25_p25_25_5 (125 floats)
    675, // lstm_aaad_x1_1_25_p25_25_5 (125 floats)
    800, // lstm_aaae_x1_1_25_p25_25_6 (25 floats)
    825, // lstm_aaae_x1_1_25_p25_25_6 (150 floats)
    975, // lstm_aaae_x1_1_25_p25_25_6 (150 floats)
    // --- Y (ground-truth outputs) ---
    1125, // lstm_aaaa_x1_1_25_p25_25_2 (25 floats)
    1150, // lstm_aaaa_x1_1_25_p25_25_2 (50 floats)
    1200, // lstm_aaaa_x1_1_25_p25_25_2 (50 floats)
    1250, // lstm_aaab_x1_1_25_p25_25_3 (25 floats)
    1275, // lstm_aaab_x1_1_25_p25_25_3 (75 floats)
    1350, // lstm_aaab_x1_1_25_p25_25_3 (75 floats)
    1425, // lstm_aaac_x1_1_25_p25_25_4 (25 floats)
    1450, // lstm_aaac_x1_1_25_p25_25_4 (100 floats)
    1550, // lstm_aaac_x1_1_25_p25_25_4 (100 floats)
    1650, // lstm_aaad_x1_1_25_p25_25_5 (25 floats)
    1675, // lstm_aaad_x1_1_25_p25_25_5 (125 floats)
    1800, // lstm_aaad_x1_1_25_p25_25_5 (125 floats)
    1925, // lstm_aaae_x1_1_25_p25_25_6 (25 floats)
    1950, // lstm_aaae_x1_1_25_p25_25_6 (150 floats)
    2100, // lstm_aaae_x1_1_25_p25_25_6 (150 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_2
    50, // lstm_aaaa_x1_1_25_p25_25_2
    50, // lstm_aaaa_x1_1_25_p25_25_2
    25, // lstm_aaab_x1_1_25_p25_25_3
    75, // lstm_aaab_x1_1_25_p25_25_3
    75, // lstm_aaab_x1_1_25_p25_25_3
    25, // lstm_aaac_x1_1_25_p25_25_4
    100, // lstm_aaac_x1_1_25_p25_25_4
    100, // lstm_aaac_x1_1_25_p25_25_4
    25, // lstm_aaad_x1_1_25_p25_25_5
    125, // lstm_aaad_x1_1_25_p25_25_5
    125, // lstm_aaad_x1_1_25_p25_25_5
    25, // lstm_aaae_x1_1_25_p25_25_6
    150, // lstm_aaae_x1_1_25_p25_25_6
    150, // lstm_aaae_x1_1_25_p25_25_6
    // --- Y (ground-truth outputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_2
    50, // lstm_aaaa_x1_1_25_p25_25_2
    50, // lstm_aaaa_x1_1_25_p25_25_2
    25, // lstm_aaab_x1_1_25_p25_25_3
    75, // lstm_aaab_x1_1_25_p25_25_3
    75, // lstm_aaab_x1_1_25_p25_25_3
    25, // lstm_aaac_x1_1_25_p25_25_4
    100, // lstm_aaac_x1_1_25_p25_25_4
    100, // lstm_aaac_x1_1_25_p25_25_4
    25, // lstm_aaad_x1_1_25_p25_25_5
    125, // lstm_aaad_x1_1_25_p25_25_5
    125, // lstm_aaad_x1_1_25_p25_25_5
    25, // lstm_aaae_x1_1_25_p25_25_6
    150, // lstm_aaae_x1_1_25_p25_25_6
    150, // lstm_aaae_x1_1_25_p25_25_6
};
