#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 0).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 5
#define X_TENSOR_COUNT 15
#define Y_TENSOR_COUNT 15
#define TENSOR_COUNT 30

static const uint32_t TOTAL_ELEMENTS = 3150; // floats in blob
static const uint32_t TOTAL_BYTES    = 12600; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 1575;
static const uint32_t Y_TOTAL_ELEMENTS = 1575;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_1 (3 inputs)
    3, // lstm_aaab_x1_1_50_p50_50_1 (3 inputs)
    6, // lstm_aaac_x1_1_100_p100_100_1 (3 inputs)
    9, // lstm_aaad_x1_1_150_p150_150_1 (3 inputs)
    12, // lstm_aaae_x1_1_200_p200_200_1 (3 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_25_p25_25_1 (3 outputs)
    3, // lstm_aaab_x1_1_50_p50_50_1 (3 outputs)
    6, // lstm_aaac_x1_1_100_p100_100_1 (3 outputs)
    9, // lstm_aaad_x1_1_150_p150_150_1 (3 outputs)
    12, // lstm_aaae_x1_1_200_p200_200_1 (3 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    25, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    50, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    75, // lstm_aaab_x1_1_50_p50_50_1 (50 floats)
    125, // lstm_aaab_x1_1_50_p50_50_1 (50 floats)
    175, // lstm_aaab_x1_1_50_p50_50_1 (50 floats)
    225, // lstm_aaac_x1_1_100_p100_100_1 (100 floats)
    325, // lstm_aaac_x1_1_100_p100_100_1 (100 floats)
    425, // lstm_aaac_x1_1_100_p100_100_1 (100 floats)
    525, // lstm_aaad_x1_1_150_p150_150_1 (150 floats)
    675, // lstm_aaad_x1_1_150_p150_150_1 (150 floats)
    825, // lstm_aaad_x1_1_150_p150_150_1 (150 floats)
    975, // lstm_aaae_x1_1_200_p200_200_1 (200 floats)
    1175, // lstm_aaae_x1_1_200_p200_200_1 (200 floats)
    1375, // lstm_aaae_x1_1_200_p200_200_1 (200 floats)
    // --- Y (ground-truth outputs) ---
    1575, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    1600, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    1625, // lstm_aaaa_x1_1_25_p25_25_1 (25 floats)
    1650, // lstm_aaab_x1_1_50_p50_50_1 (50 floats)
    1700, // lstm_aaab_x1_1_50_p50_50_1 (50 floats)
    1750, // lstm_aaab_x1_1_50_p50_50_1 (50 floats)
    1800, // lstm_aaac_x1_1_100_p100_100_1 (100 floats)
    1900, // lstm_aaac_x1_1_100_p100_100_1 (100 floats)
    2000, // lstm_aaac_x1_1_100_p100_100_1 (100 floats)
    2100, // lstm_aaad_x1_1_150_p150_150_1 (150 floats)
    2250, // lstm_aaad_x1_1_150_p150_150_1 (150 floats)
    2400, // lstm_aaad_x1_1_150_p150_150_1 (150 floats)
    2550, // lstm_aaae_x1_1_200_p200_200_1 (200 floats)
    2750, // lstm_aaae_x1_1_200_p200_200_1 (200 floats)
    2950, // lstm_aaae_x1_1_200_p200_200_1 (200 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    50, // lstm_aaab_x1_1_50_p50_50_1
    50, // lstm_aaab_x1_1_50_p50_50_1
    50, // lstm_aaab_x1_1_50_p50_50_1
    100, // lstm_aaac_x1_1_100_p100_100_1
    100, // lstm_aaac_x1_1_100_p100_100_1
    100, // lstm_aaac_x1_1_100_p100_100_1
    150, // lstm_aaad_x1_1_150_p150_150_1
    150, // lstm_aaad_x1_1_150_p150_150_1
    150, // lstm_aaad_x1_1_150_p150_150_1
    200, // lstm_aaae_x1_1_200_p200_200_1
    200, // lstm_aaae_x1_1_200_p200_200_1
    200, // lstm_aaae_x1_1_200_p200_200_1
    // --- Y (ground-truth outputs) ---
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    25, // lstm_aaaa_x1_1_25_p25_25_1
    50, // lstm_aaab_x1_1_50_p50_50_1
    50, // lstm_aaab_x1_1_50_p50_50_1
    50, // lstm_aaab_x1_1_50_p50_50_1
    100, // lstm_aaac_x1_1_100_p100_100_1
    100, // lstm_aaac_x1_1_100_p100_100_1
    100, // lstm_aaac_x1_1_100_p100_100_1
    150, // lstm_aaad_x1_1_150_p150_150_1
    150, // lstm_aaad_x1_1_150_p150_150_1
    150, // lstm_aaad_x1_1_150_p150_150_1
    200, // lstm_aaae_x1_1_200_p200_200_1
    200, // lstm_aaae_x1_1_200_p200_200_1
    200, // lstm_aaae_x1_1_200_p200_200_1
};
