#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 0).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 4
#define X_TENSOR_COUNT 4
#define Y_TENSOR_COUNT 4
#define TENSOR_COUNT 8

static const uint32_t TOTAL_ELEMENTS = 31040; // floats in blob
static const uint32_t TOTAL_BYTES    = 124160; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 3000;
static const uint32_t Y_TOTAL_ELEMENTS = 28040;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    1, // conv_aaab_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    2, // conv_aaac_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
    3, // conv_aaad_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // conv_aaaa_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    1, // conv_aaab_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    2, // conv_aaac_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
    3, // conv_aaad_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // conv_aaaa_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (100 floats)
    100, // conv_aaab_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (400 floats)
    500, // conv_aaac_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (900 floats)
    1400, // conv_aaad_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (1600 floats)
    // --- Y (ground-truth outputs) ---
    3000, // conv_aaaa_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1 (810 floats)
    3810, // conv_aaab_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1 (3610 floats)
    7420, // conv_aaac_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1 (8410 floats)
    15830, // conv_aaad_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1 (15210 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    100, // conv_aaaa_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1
    400, // conv_aaab_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1
    900, // conv_aaac_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1
    1600, // conv_aaad_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1
    // --- Y (ground-truth outputs) ---
    810, // conv_aaaa_x1_10_10_p1_10_1_None_2_2_pool_2_2_1_1
    3610, // conv_aaab_x1_20_20_p1_10_1_None_2_2_pool_2_2_1_1
    8410, // conv_aaac_x1_30_30_p1_10_1_None_2_2_pool_2_2_1_1
    15210, // conv_aaad_x1_40_40_p1_10_1_None_2_2_pool_2_2_1_1
};
