#pragma once
#include <stdint.h>

// Auto-generated by export_bin_manifest.py -- do not edit.
#define DATA_CONFIG_COUNT 20
#define FEATURE_CHANNELS 56
#define DATA_OUTPUT_CHANNELS 2

#define X_REGION_BYTE_OFFSET 0u
#define Y_REGION_BYTE_OFFSET 288000u
#define DATA_BIN_TOTAL_BYTES 1004400u

// Per-config metadata (for reporting / sanity checks)
static const uint32_t MAIN_WINDOW_LENS[20] = { 50, 50, 100, 100, 150, 150, 200, 200, 250, 250, 300, 300, 350, 350, 400, 400, 450, 450, 500, 500 };
static const uint32_t MAIN_STEPS[20] = { 1, 5, 1, 5, 1, 5, 1, 5, 1, 5, 1, 5, 1, 5, 1, 5, 1, 5, 1, 5 };
static const uint32_t MAIN_OUT_LENS[20] = { 25, 25, 50, 50, 75, 75, 100, 100, 125, 125, 150, 150, 175, 175, 200, 200, 225, 225, 250, 250 };

// Floats fed to the second model per call (= 56 * step)
static const uint32_t MAIN_INTERMEDIATE_SIZE[20] = { 56, 280, 56, 280, 56, 280, 56, 280, 56, 280, 56, 280, 56, 280, 56, 280, 56, 280, 56, 280 };

// Float-index offsets into the X region; last entry = total X floats
static const uint32_t MAIN_X_OFFSETS[21] ={0};
static const uint32_t MAIN_X_SIZES[20] = {0};

// Float-index offsets into the Y region; last entry = total Y floats
static const uint32_t MAIN_Y_OFFSETS[21] = { 0, 9000, 18000, 27000, 36000, 45000, 54000, 63000, 72000, 81000, 90000, 99000, 108000, 116750, 125500, 134300, 143100, 152100, 161100, 170100, 179100 };
static const uint32_t MAIN_Y_SIZES[20] = { 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 9000, 8750, 8750, 8800, 8800, 9000, 9000, 9000, 9000 };

// Payloads live in data.bin (flashed partition). Map them with:
//   const float* X_DATA = (const float*)(base + X_REGION_BYTE_OFFSET);
//   const float* Y_DATA = (const float*)(base + Y_REGION_BYTE_OFFSET);
