#pragma once
#include <stdint.h>

// Auto-generated by gen_brute_test_data.py (seed = 2).
// Batch 0 of 1. Blob: brute_data_0.bin
// Self-contained: offsets are LOCAL to this batch's blob.
// Layout (float32): [ X tensors ][ Y tensors ]
// All offsets/sizes are FLOAT-ELEMENT counts (x4 for bytes).

#define BENCHMARK_MODEL_DATA_COUNT 8
#define X_TENSOR_COUNT 24
#define Y_TENSOR_COUNT 24
#define TENSOR_COUNT 48

static const uint32_t TOTAL_ELEMENTS = 5220; // floats in blob
static const uint32_t TOTAL_BYTES    = 20880; // total blob size
static const uint32_t X_TOTAL_ELEMENTS = 2610;
static const uint32_t Y_TOTAL_ELEMENTS = 2610;

static const uint32_t MODEL_INPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_10_p10_10_1 (3 inputs)
    3, // lstm_aaab_x1_1_60_p60_60_1 (3 inputs)
    6, // lstm_aaac_x1_1_200_p200_200_1 (3 inputs)
    9, // lstm_aaad_x1_1_400_p400_400_1 (3 inputs)
    12, // lstm_aaae_x1_1_25_p25_25_1 (3 inputs)
    15, // lstm_aaaf_x1_1_25_p25_25_2 (3 inputs)
    18, // lstm_aaag_x1_1_25_p25_25_3 (3 inputs)
    21, // lstm_aaah_x1_1_25_p25_25_4 (3 inputs)
};

static const uint32_t MODEL_OUTPUT_INDEX[BENCHMARK_MODEL_DATA_COUNT] = {
    0, // lstm_aaaa_x1_1_10_p10_10_1 (3 outputs)
    3, // lstm_aaab_x1_1_60_p60_60_1 (3 outputs)
    6, // lstm_aaac_x1_1_200_p200_200_1 (3 outputs)
    9, // lstm_aaad_x1_1_400_p400_400_1 (3 outputs)
    12, // lstm_aaae_x1_1_25_p25_25_1 (3 outputs)
    15, // lstm_aaaf_x1_1_25_p25_25_2 (3 outputs)
    18, // lstm_aaag_x1_1_25_p25_25_3 (3 outputs)
    21, // lstm_aaah_x1_1_25_p25_25_4 (3 outputs)
};

static const uint32_t OFFSETS[TENSOR_COUNT] = {
    // --- X (inputs) ---
    0, // lstm_aaaa_x1_1_10_p10_10_1 (10 floats)
    10, // lstm_aaaa_x1_1_10_p10_10_1 (10 floats)
    20, // lstm_aaaa_x1_1_10_p10_10_1 (10 floats)
    30, // lstm_aaab_x1_1_60_p60_60_1 (60 floats)
    90, // lstm_aaab_x1_1_60_p60_60_1 (60 floats)
    150, // lstm_aaab_x1_1_60_p60_60_1 (60 floats)
    210, // lstm_aaac_x1_1_200_p200_200_1 (200 floats)
    410, // lstm_aaac_x1_1_200_p200_200_1 (200 floats)
    610, // lstm_aaac_x1_1_200_p200_200_1 (200 floats)
    810, // lstm_aaad_x1_1_400_p400_400_1 (400 floats)
    1210, // lstm_aaad_x1_1_400_p400_400_1 (400 floats)
    1610, // lstm_aaad_x1_1_400_p400_400_1 (400 floats)
    2010, // lstm_aaae_x1_1_25_p25_25_1 (25 floats)
    2035, // lstm_aaae_x1_1_25_p25_25_1 (25 floats)
    2060, // lstm_aaae_x1_1_25_p25_25_1 (25 floats)
    2085, // lstm_aaaf_x1_1_25_p25_25_2 (25 floats)
    2110, // lstm_aaaf_x1_1_25_p25_25_2 (50 floats)
    2160, // lstm_aaaf_x1_1_25_p25_25_2 (50 floats)
    2210, // lstm_aaag_x1_1_25_p25_25_3 (25 floats)
    2235, // lstm_aaag_x1_1_25_p25_25_3 (75 floats)
    2310, // lstm_aaag_x1_1_25_p25_25_3 (75 floats)
    2385, // lstm_aaah_x1_1_25_p25_25_4 (25 floats)
    2410, // lstm_aaah_x1_1_25_p25_25_4 (100 floats)
    2510, // lstm_aaah_x1_1_25_p25_25_4 (100 floats)
    // --- Y (ground-truth outputs) ---
    2610, // lstm_aaaa_x1_1_10_p10_10_1 (10 floats)
    2620, // lstm_aaaa_x1_1_10_p10_10_1 (10 floats)
    2630, // lstm_aaaa_x1_1_10_p10_10_1 (10 floats)
    2640, // lstm_aaab_x1_1_60_p60_60_1 (60 floats)
    2700, // lstm_aaab_x1_1_60_p60_60_1 (60 floats)
    2760, // lstm_aaab_x1_1_60_p60_60_1 (60 floats)
    2820, // lstm_aaac_x1_1_200_p200_200_1 (200 floats)
    3020, // lstm_aaac_x1_1_200_p200_200_1 (200 floats)
    3220, // lstm_aaac_x1_1_200_p200_200_1 (200 floats)
    3420, // lstm_aaad_x1_1_400_p400_400_1 (400 floats)
    3820, // lstm_aaad_x1_1_400_p400_400_1 (400 floats)
    4220, // lstm_aaad_x1_1_400_p400_400_1 (400 floats)
    4620, // lstm_aaae_x1_1_25_p25_25_1 (25 floats)
    4645, // lstm_aaae_x1_1_25_p25_25_1 (25 floats)
    4670, // lstm_aaae_x1_1_25_p25_25_1 (25 floats)
    4695, // lstm_aaaf_x1_1_25_p25_25_2 (25 floats)
    4720, // lstm_aaaf_x1_1_25_p25_25_2 (50 floats)
    4770, // lstm_aaaf_x1_1_25_p25_25_2 (50 floats)
    4820, // lstm_aaag_x1_1_25_p25_25_3 (25 floats)
    4845, // lstm_aaag_x1_1_25_p25_25_3 (75 floats)
    4920, // lstm_aaag_x1_1_25_p25_25_3 (75 floats)
    4995, // lstm_aaah_x1_1_25_p25_25_4 (25 floats)
    5020, // lstm_aaah_x1_1_25_p25_25_4 (100 floats)
    5120, // lstm_aaah_x1_1_25_p25_25_4 (100 floats)
};

static const uint32_t SIZES[TENSOR_COUNT] = {
    // --- X (inputs) ---
    10, // lstm_aaaa_x1_1_10_p10_10_1
    10, // lstm_aaaa_x1_1_10_p10_10_1
    10, // lstm_aaaa_x1_1_10_p10_10_1
    60, // lstm_aaab_x1_1_60_p60_60_1
    60, // lstm_aaab_x1_1_60_p60_60_1
    60, // lstm_aaab_x1_1_60_p60_60_1
    200, // lstm_aaac_x1_1_200_p200_200_1
    200, // lstm_aaac_x1_1_200_p200_200_1
    200, // lstm_aaac_x1_1_200_p200_200_1
    400, // lstm_aaad_x1_1_400_p400_400_1
    400, // lstm_aaad_x1_1_400_p400_400_1
    400, // lstm_aaad_x1_1_400_p400_400_1
    25, // lstm_aaae_x1_1_25_p25_25_1
    25, // lstm_aaae_x1_1_25_p25_25_1
    25, // lstm_aaae_x1_1_25_p25_25_1
    25, // lstm_aaaf_x1_1_25_p25_25_2
    50, // lstm_aaaf_x1_1_25_p25_25_2
    50, // lstm_aaaf_x1_1_25_p25_25_2
    25, // lstm_aaag_x1_1_25_p25_25_3
    75, // lstm_aaag_x1_1_25_p25_25_3
    75, // lstm_aaag_x1_1_25_p25_25_3
    25, // lstm_aaah_x1_1_25_p25_25_4
    100, // lstm_aaah_x1_1_25_p25_25_4
    100, // lstm_aaah_x1_1_25_p25_25_4
    // --- Y (ground-truth outputs) ---
    10, // lstm_aaaa_x1_1_10_p10_10_1
    10, // lstm_aaaa_x1_1_10_p10_10_1
    10, // lstm_aaaa_x1_1_10_p10_10_1
    60, // lstm_aaab_x1_1_60_p60_60_1
    60, // lstm_aaab_x1_1_60_p60_60_1
    60, // lstm_aaab_x1_1_60_p60_60_1
    200, // lstm_aaac_x1_1_200_p200_200_1
    200, // lstm_aaac_x1_1_200_p200_200_1
    200, // lstm_aaac_x1_1_200_p200_200_1
    400, // lstm_aaad_x1_1_400_p400_400_1
    400, // lstm_aaad_x1_1_400_p400_400_1
    400, // lstm_aaad_x1_1_400_p400_400_1
    25, // lstm_aaae_x1_1_25_p25_25_1
    25, // lstm_aaae_x1_1_25_p25_25_1
    25, // lstm_aaae_x1_1_25_p25_25_1
    25, // lstm_aaaf_x1_1_25_p25_25_2
    50, // lstm_aaaf_x1_1_25_p25_25_2
    50, // lstm_aaaf_x1_1_25_p25_25_2
    25, // lstm_aaag_x1_1_25_p25_25_3
    75, // lstm_aaag_x1_1_25_p25_25_3
    75, // lstm_aaag_x1_1_25_p25_25_3
    25, // lstm_aaah_x1_1_25_p25_25_4
    100, // lstm_aaah_x1_1_25_p25_25_4
    100, // lstm_aaah_x1_1_25_p25_25_4
};
