#pragma once
#include <stdint.h>

// Auto-generated by export_bin_manifest.py -- do not edit.
#define DATA_CONFIG_COUNT 1
#define FEATURE_CHANNELS 56
#define DATA_OUTPUT_CHANNELS 2

#define X_REGION_BYTE_OFFSET 0u
#define Y_REGION_BYTE_OFFSET 288000u
#define DATA_BIN_TOTAL_BYTES 324000u

// Per-config metadata (for reporting / sanity checks)
static const uint32_t MAIN_WINDOW_LENS[1] = { 500 };
static const uint32_t MAIN_STEPS[1] = { 1 };
static const uint32_t MAIN_OUT_LENS[1] = { 250 };

// Floats fed to the second model per call (= 56 * step)
static const uint32_t MAIN_INTERMEDIATE_SIZE[1] = { 56 };

// Float-index offsets into the X region; last entry = total X floats
static const uint32_t MAIN_X_OFFSETS[21] ={0};
static const uint32_t MAIN_X_SIZES[20] = {0};
// Float-index offsets into the Y region; last entry = total Y floats
static const uint32_t MAIN_Y_OFFSETS[2] = { 0, 9000 };
static const uint32_t MAIN_Y_SIZES[1] = { 9000 };

// Payloads live in data.bin (flashed partition). Map them with:
//   const float* X_DATA = (const float*)(base + X_REGION_BYTE_OFFSET);
//   const float* Y_DATA = (const float*)(base + Y_REGION_BYTE_OFFSET);
